Add palier1 map
aresrpg/aresrpg pull request #1
Opened 2020-09-23 21:39 UTC by DeltaEvo

2020-09-24 07:32 UTC, Sceat commented
what are the pros/cons of username based branch ?

2020-09-24 07:34 UTC, DeltaEvo commented
Just avoid name clashes, and so you know you is the "owner/referant" of this branch/feature

2020-09-24 14:05 UTC, Sceat requested changes
Looks :sparkles: overall, we have to discuss about which programming style we use, same for the casing i see you switching between camel and snake like a girl changes her clothes

PS: If you use semicolon in your code, i'll probably kill your family

2020-09-24 14:05 UTC, Sceat commented on src/settings.js
> +export const onlineMode = false;
```suggestion
const {
	VERSION     			 = '1.16',
	ONLINE_MODE: online_mode = 'false' // env variables should be treated as strings
} = process.env

export const ONLINE_MODE = `${ online_mode }`.toLowerCase() === 'true'
export { VERSION }
```

2020-09-24 16:03 UTC, DeltaEvo commented on src/entity/Player.js
> +export default class Player extends EventEmitter {
Why not using both ? I don't see very well how to represent a Player and entities with Functional Programming, but I still want to use Functional Programming on the rest of the codebase

2020-09-24 16:03 UTC, DeltaEvo commented on src/entity/Player.js
> +    this.client.on("position", ({ x, y, z, onGround }) => {
This is the default config of prettier, i don't mind

2020-09-24 16:08 UTC, DeltaEvo commented on src/entity/Player.js
> +  }
I don't think it's a mistake, here I want the side effect to not have to think about chunk loading, only two things affect chunk loading, viewDistance and position, I could have used events for this but I don't know, I like this solution

2020-09-24 16:08 UTC, DeltaEvo commented on src/entity/Player.js
> +      dimension: "minecraft:overworld",
This is not the same think :upside_down_face:, it's a dimension id, minecraft being minecraft it's the same name of a world but it might change

2020-09-24 16:08 UTC, DeltaEvo commented on src/entity/Player.js
> +    this.viewDistance = 3;
And i don't want to handle chunk update everywhere i change state of my Player

2020-09-24 16:14 UTC, DeltaEvo commented on src/math.js
> +        )
tacit programming is a abstract thing, if you have a better way to write this go ahead

2020-09-24 16:14 UTC, DeltaEvo commented on src/math.js
> +}
There is no sense to curry such a function
I will change the parameters

2020-09-24 16:16 UTC, DeltaEvo commented on src/settings.js
> +export const onlineMode = false;
I don't want the version to be configurable
But i will do this for onlineMode

2020-09-24 18:04 UTC, DeltaEvo commented on src/entity/Player.js
> +    const worldNames = ["minecraft:overworld"];
Yep, but this is not a constant, i'll add a TODO

2020-09-24 18:33 UTC, DeltaEvo commented on src/math.js
> +        )
I rewrote this function tell me what you think

2020-09-24 20:07 UTC, Sceat commented on src/entity/Player.js
> +export default class Player extends EventEmitter {
using both will cause ambiguity later on, i'll write a FP version tomorrow morning to discuss about the differences

2020-09-24 20:09 UTC, Sceat commented on src/entity/Player.js
> +      dimension: "minecraft:overworld",
@markusperson prefer using brain cells when writing code

2020-09-24 20:10 UTC, Sceat commented on src/entity/Player.js
> +    this.viewDistance = 3;
And i would prefer fat ladies to just not exists

2020-09-24 20:19 UTC, Sceat commented on src/math.js
> +        )
hum having a hard time understanding the point of binding to `null`, insn't that exactly the point of an arrow function ? 

```js
  const is_inside_a = is_inside.bind(null, {
    min: { x: ax - demi_length, y: ay - demi_length },
    max: { x: ax + demi_length, y: ay + demi_length },
  })
```

2020-09-24 21:29 UTC, DeltaEvo commented on src/math.js
> +        )
null is for the this, not it is not, it's partial application in javascript :)

2020-09-24 22:42 UTC, DeltaEvo commented on src/entity/Player.js
> +export default class Player extends EventEmitter {
I don't see why it will cause ambiguity, we use JavaScript a multi paradigm language to only limit ourself to one paradigm instead of picking the best/easiest one based on what we need to implement ?

2020-09-26 19:30 UTC, Sceat approved these changes
This is what i call a fucking piece of art ✔️ 

![image](https://user-images.githubusercontent.com/11330271/94348818-85a42980-003f-11eb-9fcf-95c6dfe8048c.png)

2020-09-26 21:08 UTC, merged