Adding Mob Damages
aresrpg/aresrpg pull request #100
Opened 2021-01-09 19:51 UTC by ToufouMaster

2021-01-10 08:49 UTC, DeltaEvo requested changes

2021-01-10 08:49 UTC, DeltaEvo commented on src/mobs/fight.js
> +  /* if (newlife > 0) {
Can you remove this comment ?

2021-01-10 19:36 UTC, ToufouMaster commented on src/mobs/fight.js
> +  /* if (newlife > 0) {
sry

2021-01-11 10:52 UTC, DeltaEvo commented on src/mobs.js
> +      life: 20 /* halfheart */,
I think `health` is more appropriate here

2021-01-17 07:44 UTC, DeltaEvo approved these changes

2021-01-17 07:45 UTC, ToufouMaster commented
Et bah voila
xD

2021-01-17 07:47 UTC, merged