Implement health and fall damages
aresrpg/aresrpg pull request #131
Opened 2021-02-16 05:02 UTC by Sceat

2021-02-16 05:03 UTC, Sceat commented
seems that i missed something with the `dispatch` :thinking: i never get my action

```js
log.debug({ fall_distance, damage }, 'has fallen')
if (damage > 0) dispatch('fall_damage', { damage })
```

```
packet/position
packet/position
packet/position
packet/position
packet/position
packet/position
packet/position
packet/position
packet/position
0000033543 player/fall_dama  D  has fallen { fall_distance: 4.919999986886978, damage: 0.9599999934434891 }
packet/keep_alive
packet/position
packet/position
packet/position
packet/position
packet/position
packet/position
packet/keep_alive
packet/position
```

2021-02-16 05:47 UTC, Sceat commented
seems to be caused by the combine async iterator lib 🤡

2021-02-16 06:52 UTC, DeltaEvo commented
Oups, my bad, combineAsyncIteratot expect to have async iterator and actions is an async iterable so it takes it as the options object, to fix that we can do
```js
combineAsyncIterators(actions[Symbol.asyncIterator](), packets)
```

2021-02-17 01:06 UTC, Sceat commented
PR is kinda done, just need to figure out why
```js
client.write('update_health', {
          health,
          food: 20,
          foodSaturation: 0,
        })
```
doesn't update the client health bar

2021-02-17 01:40 UTC, Sceat commented
for whatever reason we cannot send more than `20` of health :thinking:

2021-02-17 07:06 UTC, DeltaEvo commented
Maybe you should send a https://wiki.vg/Protocol#Entity_Properties to updqte it's max health before

2021-02-17 07:07 UTC, Sceat commented
okay well i forgot everything about this game damn me

2021-02-17 07:10 UTC, Sceat commented
![image](https://user-images.githubusercontent.com/11330271/108168395-870de580-70f7-11eb-9d41-639dc1baad26.png)
![Uploading image.png…]()

2021-02-18 20:59 UTC, DeltaEvo requested changes
Just some little things but seems good otherwise

2021-02-18 20:59 UTC, DeltaEvo commented on src/player/fall_damage.js
> +    if (type !== 'fall_damage') return state
Can you invert the condition and the branches ?

2021-02-18 20:59 UTC, DeltaEvo commented on src/position.js
> +  if (!types.includes(type)) return state
Can you reinvert the condition ?

2021-02-18 20:59 UTC, DeltaEvo commented on src/player/health.js
> +    }
Can you inline this reducer ?

2021-02-18 22:12 UTC, DeltaEvo approved these changes

2021-02-18 22:12 UTC, merged