Stats and Weapon Damages
aresrpg/aresrpg pull request #144
Opened 2021-02-21 19:02 UTC by ToufouMaster

added Basic Weapon Damages
added Critical damage
added Weapon Statistics + Player Statistics

2021-02-21 20:13 UTC, DeltaEvo requested changes

2021-02-21 20:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +          }
Why do you have it two times ?

2021-02-21 20:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      strength = Math.max(0, strength)
How this could be negative :thinking: ?

2021-02-21 20:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      }
Can you try to avoid mutation `weaponDamage`, `dexterity`, `strength`. `dmg` and introduce a variable for each part like
```js
const player_stats = { strength: ..., dexterity: ... } // All stats of player
const weapon = { damage: ..., critical: ... }

const armor_stats = { strength: ... } // All stats of armor
 
const is_critical =  ...
const damage_multiplier = is_critical ? 1.6 : 1

const strength = player.stats.strength + armor_stats.strength
const damage = Math.floor((1 + weapon.damage + strength * 0.5) * damage_multiplier)
```

2021-02-21 20:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +          is_critical,
Why do you need is_critical here ?

2021-02-21 20:16 UTC, ToufouMaster commented on src/mobs/fight.js
> +      strength = Math.max(0, strength)
at the start some armor or artefact can set strength to negative

2021-02-21 20:19 UTC, ToufouMaster commented on src/mobs/fight.js
> +          }
done

2021-02-22 08:15 UTC, ToufouMaster commented on src/mobs/fight.js
> +      let dexterity = stats[4].value
how?

2021-02-22 08:25 UTC, DeltaEvo commented on src/mobs/fight.js
> +      let dexterity = stats[4].value
By using an object instead of an array for stats

2021-02-22 08:39 UTC, ToufouMaster commented on src/mobs/fight.js
> +          is_critical,
for display in log

Deal Damage { damage: 654, health: 0, is_critical: false }

2021-02-22 08:39 UTC, ToufouMaster commented on src/mobs/fight.js
> +      }
done

2021-02-22 08:39 UTC, DeltaEvo commented on src/mobs/fight.js
> +          is_critical,
I don't think the mob will need to know if the damage is critical

2021-02-22 08:41 UTC, ToufouMaster commented on src/mobs/fight.js
> +          is_critical,
hmm and when the mob take damage we are going to display his life at top of him don't we need is_critical for display his life in red?

2021-02-22 08:43 UTC, DeltaEvo commented on src/mobs/fight.js
> +          is_critical,
I don't think this will be handled here, so if you are planing to implement it in this PR, fine, but otherwise I prefer to see where to pass is_critical when we will implement the damages indicators

2021-02-22 08:44 UTC, ToufouMaster commented on src/mobs/fight.js
> +          is_critical,
okay

2021-02-22 08:44 UTC, ToufouMaster commented on src/mobs/fight.js
> +          is_critical,
done

2021-02-22 09:06 UTC, DeltaEvo requested changes

2021-02-22 09:06 UTC, DeltaEvo commented on src/mobs/fight.js
> +            weapon.critical += itemData.critical * 100 * 4
Try to avoid mutating weapon

2021-02-22 09:06 UTC, DeltaEvo commented on src/mobs/fight.js
> +            armor_stats.strength += itemData.stats.strength
Try to avoid mutating armor_stats

2021-02-22 09:06 UTC, DeltaEvo commented on src/mobs/fight.js
> +      player_stats.strength = Math.max(0, player_stats.strength)
Try to avoid mutating player_stats

2021-02-22 09:06 UTC, DeltaEvo commented on src/mobs/fight.js
> +      let is_critical = false
`const is_critical = rand < critc`

2021-02-22 09:13 UTC, ToufouMaster commented on src/mobs/fight.js
> +          weapon.damage = minDamage + Math.random() * (maxDamage - minDamage)
how can i do other way than this

2021-02-22 09:13 UTC, ToufouMaster commented on src/mobs/fight.js
> +            weapon.critical += itemData.critical * 100 * 4
how can i do other way than this

2021-02-22 09:13 UTC, ToufouMaster commented on src/mobs/fight.js
> +            armor_stats.strength += itemData.stats.strength
how can i do other way than this

2021-02-22 09:13 UTC, ToufouMaster commented on src/mobs/fight.js
> +      player_stats.strength = Math.max(0, player_stats.strength)
how can i do other way than this

2021-02-22 09:14 UTC, DeltaEvo commented on src/mobs/fight.js
> +          weapon.damage = minDamage + Math.random() * (maxDamage - minDamage)
With a function that return the weapon_damage for example

2021-02-22 09:15 UTC, DeltaEvo commented on src/mobs/fight.js
> +            armor_stats.strength += itemData.stats.strength
By using functional iteration on array, 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2021-02-22 09:16 UTC, DeltaEvo commented on src/mobs/fight.js
> +      player_stats.strength = Math.max(0, player_stats.strength)
You can introduce a new constant for that

2021-02-28 13:43 UTC, ToufouMaster commented on src/mobs/fight.js
> +      let dexterity = stats[4].value
done

2021-02-28 13:47 UTC, ToufouMaster commented on src/mobs/fight.js
> +          weapon.damage = minDamage + Math.random() * (maxDamage - minDamage)
done i think

2021-02-28 13:48 UTC, ToufouMaster commented on src/mobs/fight.js
> +            weapon.critical += itemData.critical * 100 * 4
done

2021-02-28 14:59 UTC, ToufouMaster commented on src/mobs/fight.js
> +            armor_stats.strength += itemData.stats.strength
done

2021-02-28 14:59 UTC, ToufouMaster commented on src/mobs/fight.js
> +      player_stats.strength = Math.max(0, player_stats.strength)
done i think

2021-02-28 14:59 UTC, ToufouMaster commented on src/mobs/fight.js
> +      let is_critical = false
done

2021-02-28 15:13 UTC, DeltaEvo requested changes

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      }
Can you transform the stats object in state instead ?

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +          weapon.damage = minDamage + Math.random() * (maxDamage - minDamage)
No, you are still mutating (modifying) the weapon object

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
Avoid mutating the itemStats object

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      for (const key of Object.keys(itemStats)) {
You can use https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/entries to also have the value

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +}
You don't need to create a function for that

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +}
You don't need to create a function for that

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +}
You don't need to create a function for that

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +          }
```suggestion
        weapon.critical += get_weapon_critical(itemData) ?? 0
```

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      const critc = Math.min(50, 1 + dexterity / 4)
Maybe rename that `critical_chance` ?

2021-02-28 15:13 UTC, DeltaEvo commented on src/mobs/fight.js
> +      console.log(strength, dexterity)
Remove this `console.log`

2021-02-28 15:14 UTC, DeltaEvo commented on src/mobs/fight.js
> +          }
https://javascript.info/nullish-coalescing-operator

2021-02-28 15:36 UTC, ToufouMaster commented on src/mobs/fight.js
> +      console.log(strength, dexterity)
oups done

2021-02-28 15:37 UTC, ToufouMaster commented on src/mobs/fight.js
> +      const critc = Math.min(50, 1 + dexterity / 4)
done

2021-02-28 15:39 UTC, ToufouMaster commented on src/mobs/fight.js
> +          }
done

2021-02-28 15:40 UTC, ToufouMaster commented on src/mobs/fight.js
> +}
done

2021-02-28 15:40 UTC, ToufouMaster commented on src/mobs/fight.js
> +}
done

2021-02-28 15:41 UTC, ToufouMaster commented on src/mobs/fight.js
> +}
done

2021-02-28 15:43 UTC, ToufouMaster commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
i see no other way for doing that

2021-02-28 15:44 UTC, ToufouMaster commented on src/mobs/fight.js
> +      }
done

2021-02-28 15:46 UTC, ToufouMaster commented on src/mobs/fight.js
> +      for (const key of Object.keys(itemStats)) {
done

2021-02-28 15:46 UTC, ToufouMaster commented on src/mobs/fight.js
> +}
done

2021-02-28 16:03 UTC, DeltaEvo commented on src/mobs/fight.js
> +      }
What i was meaning is make the stats object inside the state an object not renaming stats to state

So i want you to change this https://github.com/aresrpg/aresrpg/pull/144/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R81-R88

2021-02-28 16:03 UTC, DeltaEvo commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
You can use 
developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce to do that

2021-02-28 16:04 UTC, DeltaEvo commented on src/mobs/fight.js
> +          weapon.damage = minDamage + Math.random() * (maxDamage - minDamage)
Nop, you are still mutating (modifying) the weapon object :p

2021-02-28 16:22 UTC, ToufouMaster commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
oh i see

2021-02-28 17:37 UTC, DeltaEvo commented on src/mobs/fight.js
> +      }
Still not good :(, I don't want you to rename it just make an objects with the stats like
```js
 stats: {
  strength: 0,
  ...
}
```

2021-02-28 17:38 UTC, DeltaEvo commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
A little bit better but you are still mutating the object

2021-02-28 17:39 UTC, ToufouMaster commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
explain yourself

2021-02-28 17:42 UTC, DeltaEvo commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
`itemStats[key] += ` modify the object itemStats, I want you to not modify the object, with reduce you can create a new object at each iteration/execution

2021-02-28 17:50 UTC, ToufouMaster commented on src/mobs/fight.js
> +          itemStats[key] += itemData.stats[key]
can you go in vocal?

2021-03-02 16:35 UTC, DeltaEvo commented on src/mobs/fight.js
> +  }
Use `reduce` here instead of reassigning `stats`

2021-03-02 16:36 UTC, ToufouMaster commented on src/mobs/fight.js
> +      }
done

2021-03-02 16:36 UTC, ToufouMaster commented on src/mobs/fight.js
> +  }
reduce inside reduce?

2021-03-02 16:41 UTC, DeltaEvo commented on src/mobs/fight.js
> +  }
reduce on top of a reduce :upside_down_face: But yes you will have two reduces

2021-03-02 16:44 UTC, ToufouMaster commented on src/mobs/fight.js
> +  }
the goal is to not mutate stats?

2021-03-02 16:49 UTC, DeltaEvo commented on src/mobs/fight.js
> +  }
Not reassign the `stats` local variable

2022-12-21 07:56 UTC, Sceat commented
deprecated

2022-12-21 07:56 UTC, closed without merging