Zekirax/commands
aresrpg/aresrpg pull request #156
Opened 2021-02-28 13:53 UTC by Zekirax

2021-02-28 14:29 UTC, DeltaEvo requested changes

2021-02-28 14:29 UTC, DeltaEvo commented on src/commands/msg.js
> +  world.events.emit('private message', { receiver_username: args[0], options }) // args[0] is the username
Maybe create a `username` variable instead of `args[0] is the username`

2021-02-28 14:29 UTC, DeltaEvo commented on src/commands/msg.js
> +          properties: 0x02, // 0x02 for only player entity
Can you create a constant for that ?

2021-02-28 14:29 UTC, DeltaEvo commented on src/commands/msg.js
> +              command_node_type: 2,
Maybe we should create a constant for that

2021-02-28 14:29 UTC, DeltaEvo commented on src/player/chat.js
> +    world.events.on('private message', ({ receiver_username, options }) => {
Try to avoid using spaces in event names, `private_message` is better

2021-02-28 14:45 UTC, Zekirax commented on src/commands/msg.js
> +          properties: 0x02, // 0x02 for only player entity
what is "that"? Be more precise

2021-02-28 14:45 UTC, Zekirax commented on src/commands/msg.js
> +              command_node_type: 2,
what is "that"? Be more precise

2021-02-28 15:06 UTC, DeltaEvo commented on src/commands/msg.js
> +          properties: 0x02, // 0x02 for only player entity
that, is the line on which I made the comment, but to be more precise, create a constant for the magic number `0x2`

2021-02-28 15:07 UTC, DeltaEvo commented on src/commands/msg.js
> +              command_node_type: 2,
The `2` constant for the command_node_type

2021-02-28 16:07 UTC, DeltaEvo requested changes
Nice :+1:, just two small little changes :)

2021-02-28 16:07 UTC, DeltaEvo commented on src/commands/declare_options.js
> +}
Can you name that with CamelCase so `parser_properties` => `ParserProperties` and `command_node_types` => `CommandNodeTypes`

2021-02-28 16:08 UTC, DeltaEvo commented on src/commands/msg.js
> +  const [username, ...message_words] = args
Perfect :+1:

2021-02-28 16:49 UTC, Zekirax commented on src/commands/msg.js
> +  const [username, ...message_words] = args
I know. I'm the best.

2021-03-01 13:09 UTC, DeltaEvo approved these changes

2021-03-01 13:10 UTC, merged