Added bot system
aresrpg/aresrpg pull request #211
Opened 2021-06-15 09:01 UTC by NEXOmega

**TODO :** 

- Re-Enable Ressource Pack, disabled because bot would not accept it and stay blocked before joining server
- Finish Command to start test individually

2021-06-26 19:42 UTC, DeltaEvo commented on package.json
> +    "mineflayer-move": "github:cheezbarger/mineflayer-move",
This should be moved to devDependencies

2021-06-26 19:45 UTC, DeltaEvo requested changes
Nice ! Thanks for taking the time to implement that, but I don't think it should be part of the "main" code we should separate the tests from the code,
also I was thinking to use https://jestjs.io/ for the tests

Can you try to separate what you did from the main code (inside a `test` folder instead of `src`) ?

2021-08-16 19:34 UTC, Sceat commented
> Nice ! Thanks for taking the time to implement that, but I don't think it should be part of the "main" code we should separate the tests from the code,
> also I was thinking to use [jestjs.io](https://jestjs.io/) for the tests
> 
> Can you try to separate what you did from the main code (inside a `test` folder instead of `src`) ?

We could also use https://github.com/HydreIO/doubt

2021-08-25 16:56 UTC, Sceat requested changes
Thanks again 🎉

2021-08-25 16:56 UTC, Sceat commented on package.json
> +    "test": "node --experimental-vm-modules ./node_modules/jest/bin/jest.js",
Let's discuss before futher implementation as i actually tried Jest and it sucks with esmodules, really don't think we should use it, @hydre/doubt or node-tap are great.

2021-08-25 16:56 UTC, Sceat commented on src/index.js
> +    await player_resource_pack.observe(context)
probably @DeltaEvo will know how to handle this

2021-08-25 16:56 UTC, Sceat commented on tests/bot.js
> +import mineflayer from 'mineflayer'
the folder name should be `test`

2021-08-25 16:56 UTC, Sceat commented on tests/connected.test.js
> +    expect(data).toBeTruthy()
this is great! i like the idea of simply implementing a testing base

2021-08-25 16:56 UTC, Sceat commented on tests/connected.test.js
> +}
```suggestion
import { expect, test } from '@jest/globals'
import { once } from 'events'

import bot from './bot.js'

const connected = () => events.once(bot, 'spawn')
```

2022-12-21 07:18 UTC, Sceat commented
closing for inactivity

2022-12-21 07:18 UTC, closed without merging