Add a attack_target behavior node
aresrpg/aresrpg pull request #234
Opened 2021-08-02 09:36 UTC by DeltaEvo

2021-08-20 19:07 UTC, Sceat reviewed
What's the state of this PR ?

2021-08-20 19:07 UTC, Sceat commented on src/mobs/attack.js
> +      aiter(on(mob.events, 'state')).reduce(
might need to update with abortable

2021-08-20 19:07 UTC, Sceat commented on src/player/health.js
> +  },
this already exist in the `master` branch :thinking:

2021-11-29 00:20 UTC, Sceat requested changes

2021-11-29 00:20 UTC, Sceat commented on src/behavior/attack_target.js
> +  } else if (state.target_position == null) {
i don't see where you are actually using the difference between `null` and `undefined` cuz if it's unused we should stick to only one representation of emptyness for simplicity 🤔

2021-11-29 00:20 UTC, Sceat commented
u have a conflict

2021-11-29 08:04 UTC, DeltaEvo commented on src/behavior/attack_target.js
> +  } else if (state.target_position == null) {
I am not using that `== null` (not the double equal) will match for null and undefined

2021-11-29 19:32 UTC, Sceat commented on src/behavior/attack_target.js
> +  } else if (state.target_position == null) {
i assume that if you don't use `(!state.target)` it's because you want to differentiate `null` and `undefined` so that `undefined` means it was just created and `null` means it lost his target, but if you don't use such behaviour then why using `null` at all

2021-12-05 12:10 UTC, Sceat approved these changes

2021-12-05 12:14 UTC, merged