Implement a permanent storage
aresrpg/aresrpg pull request #262
Opened 2021-08-16 22:00 UTC by Sceat

Here are some ideas of a structure we could use, please review and let's discuss.

2021-08-17 07:23 UTC, DeltaEvo commented
Some early thoughts:
- I don't think we have the need for redis graph, we won't have a lot of relations (I don't think we will have relations at all), I think a bare redis will do the work and be easier we could switch later if needed
- Loading a player from database should not use the classic observer/reducer struct instead it should provide the initial_state of the player

```javascript
let state = initial_state
if (USE_PERSISTANT_STORAGE)
  state = load_from_database(initial_state, client.uuid)
```

2021-08-17 07:27 UTC, DeltaEvo commented on src/database/graph.js
> +export default new Proxy({}, handler)
Why are you using a proxy for that, it seems a bit overkill for me, can you not just create yhe "noop" object yourself ?

2021-08-17 07:27 UTC, DeltaEvo commented on src/database/graph.js
> +if (USE_STORAGE?.toLowerCase() === 'true') {
You can move USE_STORAGE into settings.js and do the convertion to a boolean here

2021-08-17 07:44 UTC, Sceat commented
I'm afraid redis is a bit limited as a database, basic stuff like secondary key indexing needs us to do more work, redisearch is good but still limited and more overhead to learn that redisgraph (and still not a database), look at the doc for Disk :/ the choice for me is either mongodb or redisgraph, while mongodb force us to express relations with foreign keys

2021-08-17 07:54 UTC, DeltaEvo commented
> I'm afraid redis is a bit limited as a database, basic stuff like secondary key indexing needs us to do more work, redisearch is good but still limited and more overhead to learn that redisgraph (and still not a database), look at the doc for Disk :/ the choice for me is either mongodb or redisgraph, while mongodb force us to express relations with foreign keys

The thing is that for me we will not need to use the complex parts of redisearch, for the game data we only need a Map<UUID, JSON>, so no secondary key, we don't even need a structure since we will only access the data as a whole, I think we should just store the json as a string first in redis, then if we need to acces part of the data use redisjson (maybe the website will need that)

2021-08-17 07:57 UTC, Sceat commented
Forgot the existence of redisjson 👍 that's indeed the best and simplest choice for us

2021-08-17 21:05 UTC, Sceat commented
PR is ready :+1: yet there is an infinite amount of typing error, deal with it

2021-08-22 13:10 UTC, DeltaEvo requested changes

2021-08-22 13:10 UTC, DeltaEvo commented on src/database/sentinel.js
> +new Set([master_client, slave_client]).forEach((client) => {
You don't need to create a set here

2021-08-22 13:10 UTC, DeltaEvo commented on src/database/sentinel.js
> +  client.on('error', () => {})
Don't ignore error of clients, log them or let them be unhandled

2021-08-22 13:10 UTC, DeltaEvo commented on src/database/sentinel.js
> +log.info({ master: true, slave: true }, 'redis cluster initialized')
Why do we need to have `{ master: true, slave: true }` if it's constant ?

2021-08-22 13:10 UTC, DeltaEvo commented on src/database/sentinel.js
> +const probe_status = {
Why do we need to probe the status ?

2021-08-22 13:15 UTC, DeltaEvo commented on src/database/index.js
> +  push: async (state) => {
```suggestion
  async push(state) {
```

2021-08-22 13:15 UTC, DeltaEvo commented on src/database/index.js
> +  pull: async () => {
```suggestion
  async pull() {
```

2021-08-22 13:15 UTC, DeltaEvo commented on src/database/sentinel.js
> +const retryStrategy = (label) => (attempt) => {
snake_case ?
I would prefer that you use functions instead of array functions for top level functions

2021-08-22 13:15 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
named exports ?

2021-08-22 13:17 UTC, Sceat commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
redis sentinel is an alternative to a cluster, since i already had a compact code from Sidy i just used it
read more here https://stackoverflow.com/questions/31143072/redis-sentinel-vs-clustering

2021-08-22 13:19 UTC, Sceat commented on src/database/sentinel.js
> +const probe_status = {
it makes the module kubernetes ready

2021-08-22 13:26 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
Is it really ? I just read the documentation of redis, so I might be wrong, but from what I understood sentinel only monitor and manage the cluster

But even with that information I don't think we should "handle" the shape of the redis deployment in our code, the library should handle that

2021-08-22 13:36 UTC, DeltaEvo commented on src/database/sentinel.js
> +const probe_status = {
Can you explain why ?

2021-08-22 18:28 UTC, Sceat commented on src/index.js
> +    await storage.push(get_state())
how do i get that ?

2021-08-22 18:33 UTC, Sceat commented on src/database/sentinel.js
> +const probe_status = {
if the redis connection is lost, it allows the k8s scheduler to not move load to the current pod, we'll have to simply implement a socket/http response to whatever route we configure in k8s (like `/health`)

Should we terminate the process if there are players on this instance ? the drop could last just the time for k8s to reboot redis, Ioredis has a queue to replay commands that hapenned while it was reconnecting.

There could be a flow in this, if all pods can't contact redis well they may all be restarted i'm don't remember well how the scheduler respond to probes status but this discussion should be detailed when we host stuff.

2021-08-22 18:33 UTC, Sceat commented on src/database/index.js
> +  push: async (state) => {
what's the difference ?

2021-08-22 18:34 UTC, Sceat commented on src/database/sentinel.js
> +const retryStrategy = (label) => (attempt) => {
does that change anything ?

2021-08-22 18:43 UTC, Sceat commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
it designate new masters and manage replicas but that's different from the official "redis-cluster" image.
Would be better to not handle it but that's very specific with redis, you only have one client in normal deployments where you read and write, with sentinel you have a master and many slaves to read from. You also can't move from a simple redis to a clustered redis without dumping and importing again with the cluster system in mind. Sentinel is kinda an enhanced version of the simple client and that's the best we can use without needing to deploy a minimum of 6 instance (which requires a more heavy and expensive k8s)
![image](https://user-images.githubusercontent.com/11330271/130366335-a0ec77da-a5f1-4443-918c-22085584ce15.png)

So this "shape selection" is actually a constant (we may never need a cluster unless we reach ten of thousands of players) without this file we can't use sentinel, or we should write an external module exporting a read and write client (overkill ?)

2021-08-22 18:55 UTC, Sceat commented on src/database/sentinel.js
> +new Set([master_client, slave_client]).forEach((client) => {
I don't but that was an eslint rule (don't remember which one)

2021-08-22 19:23 UTC, DeltaEvo commented on src/index.js
> +    await storage.push(get_state())
The reduce here https://github.com/aresrpg/aresrpg/blob/master/src/index.js#L236 return a promise that will resolve with the last state value

2021-08-22 19:35 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
Can we not create one client and use the read-write splitting of ioredis ?

For the sentinel configuration I think we should make it optional and change the docker compose to be dead simple and only have a rejson master and only use the sentinel option on the production cluster

2021-08-22 19:38 UTC, DeltaEvo commented on src/database/sentinel.js
> +const probe_status = {
Ok but currently we terminate the process directly, so the probe_status will never be used, I think we should remove it since we don't know yet how we will implement that and a boolean flag might not be enough

2021-08-22 19:39 UTC, DeltaEvo commented on package.json
> +    "@aresrpg/aresrpg-map-colors": "^1.1.2",
Don't update the deps in this PR

2021-08-22 19:43 UTC, DeltaEvo commented on src/database/index.js
> +  push: async (state) => {
Follow the current style of the codebase and I don't see the need of an arrow function here, it's not an anonymous function and you don't need to use the lexical `this`

2021-08-22 19:45 UTC, Sceat commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
ioredis support read/write for clusters only, we can switch back to a single redis node but we'll have to get sentinel pretty quickly anyway (or switch directly to a cluster ?)

2021-08-22 20:06 UTC, DeltaEvo commented on package.json
> +    "@aresrpg/aresrpg-map-colors": "^1.1.2",
Mhh it seems that you are downgrading a dependency :thinking:

2021-08-22 20:13 UTC, DeltaEvo commented on src/index.js
> +      })
You don't need to do that in the `once('end'` :smile: 
This mean that you can avoid introducing a local variable and chain the `.then(state)` after the reduce

2021-08-22 20:13 UTC, DeltaEvo commented on src/index.js
> +  const events = new EventEmitter()
Can you reput that line where it was ? (Before the aiter)

2021-08-22 20:13 UTC, DeltaEvo commented on src/database/sentinel.js
> +const retryStrategy = (label) => (attempt) => {
I unresolved this since this is still in camelCase

2021-08-22 20:15 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
I don't see why read/write splitting would not work with sentinel :thinking:

2021-08-22 20:16 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
Ah got it it's on a `Redis.Cluster` object

2021-08-22 20:18 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
https://github.com/luin/ioredis/blob/master/lib/redis/RedisOptions.ts#L9-L11 RedisOptions extends the IClusterOptions so you can use `scaleReads` on a bare redis client :)

2021-08-22 20:19 UTC, Sceat commented on package.json
> +    "@aresrpg/aresrpg-map-colors": "^1.1.2",
dang wtf i copy paster master

2021-08-22 20:23 UTC, Sceat commented on src/database/sentinel.js
> +const retryStrategy = (label) => (attempt) => {
oooops

2021-08-22 20:26 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
we can give it but it's not used :(

2021-08-22 20:30 UTC, Sceat commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
get rekt

2021-08-22 20:33 UTC, DeltaEvo commented on src/database/sentinel.js
> +export { master_client, slave_client, probe_status }
I will resolve that since I don't see how to do better then :\

2021-08-22 20:35 UTC, DeltaEvo commented on src/index.js
> +  client.on('error', (error) => log.error(error, 'Client error'))
Can you reput that where it was ?

2021-08-22 20:36 UTC, Sceat commented on src/index.js
> +  client.on('error', (error) => log.error(error, 'Client error'))
xD hey!!

2021-08-22 20:37 UTC, DeltaEvo approved these changes

2021-08-22 21:17 UTC, merged