Visual responses from gaining XP and Levels
aresrpg/aresrpg pull request #330
Opened 2021-10-18 23:47 UTC by Sceat

2021-10-18 23:47 UTC, Sceat commented
only thing missing for #325 is to send a msg to nearby players, but even looking at #288 i'm not sure yet how to do that

2021-10-19 04:26 UTC, DeltaEvo commented
For that you need to send an event on the world with as payload the chat message a position (and maybe a radius), listen this event and the position of the player is within the radius, send the message

2021-10-19 10:56 UTC, Sceat commented
this is also missing https://hastebin.com/epomujevuz.java

2021-11-11 21:07 UTC, DeltaEvo requested changes

2021-11-11 21:07 UTC, DeltaEvo commented on src/context.js
> +  },
I don't think we need to store the available_points since you can compute that with the level and the used points

2021-11-11 21:07 UTC, DeltaEvo commented on src/context.js
> +  max_health: 40,
I don't think we need to store the max_health since this can be computed

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +  return current_level
Why did you changed that ?

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +  return Math.round((100 * current_level_progression) / required_experience)
I don't think the convertions to percents should be donne here

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +  const next_level_experience = levels[current_level + 1]
You don't handle the case where `current_level` is the last level and there is no level after that

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +    } else if (type === 'player/new_level') {
We should be able to detect a new level directly when we have a add_experience

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +          last_level: 1,
This initial state doesn't seems right, what if the player is not level 1 🤔

2021-11-11 21:07 UTC, DeltaEvo commented on src/player/experience.js
> +            last_level: current_level,
Do we really need to store the last_level here, the last_total_experience doesn't already have this information ?

2021-11-11 22:10 UTC, Sceat commented on src/player/experience.js
> +  return current_level
Code wasn't working properly (also ambiguous)

2021-11-11 22:12 UTC, Sceat commented
Oii this review will need to make my brain do maths and i'm bad at it 😵

2021-11-30 22:38 UTC, DeltaEvo approved these changes

2021-11-30 23:41 UTC, merged