Prevent a player in creative mode from taking damages
aresrpg/aresrpg pull request #361
Opened 2021-11-14 19:28 UTC by Sceat

2021-11-14 21:51 UTC, DeltaEvo requested changes

2021-11-14 21:51 UTC, DeltaEvo commented on src/player/damage.js
> +  [kUndefined]: () => {
`({ [undefined]: 1 })[undefined]` or  `({ [null]: 1 })[null]` works too :)

2021-11-14 21:51 UTC, DeltaEvo commented on src/player/damage.js
> +
I don't really see the need for that, I prefer that we add it we we will have more than one damage source

2021-11-14 23:55 UTC, Sceat commented on src/player/damage.js
> +
I replace the `FALL_DAMAGE` action by a generic `DAMAGE` one so still need pattern matching here, that small addition is quite mild

2021-11-16 22:58 UTC, DeltaEvo approved these changes

2021-11-17 09:20 UTC, merged