Send an action bar to the player
aresrpg/aresrpg pull request #363
Opened 2021-11-14 23:42 UTC by Sceat

2021-11-27 22:09 UTC, DeltaEvo requested changes

2021-11-27 22:09 UTC, DeltaEvo commented on src/player/action_bar.js
> +  return `#${('000000' + hue.toString(16)).slice(-6)}`
`padStart` instead of the `'000000'` + `slice(-6)`

2021-11-27 22:09 UTC, DeltaEvo commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
You need to pass the signal to the setInterval, to be able to cancel it when the player disconnect

2021-11-27 22:09 UTC, DeltaEvo commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
Also why are you updating it each 2 seconds nothing seems to be time based here ?

2021-11-27 22:09 UTC, DeltaEvo commented on src/player/action_bar.js
> +        // might be costly :/
Why ?

2021-11-27 22:09 UTC, DeltaEvo commented on src/chat.js
> +  client.write('chat', {
There is also a dedicated action bar packet, I think we should use it

2021-11-27 22:09 UTC, DeltaEvo commented on src/player/action_bar.js
> +          [last_health, last_max_health, last_remaining_stats_point],
Why this is an array and not an object ?

2021-11-27 22:12 UTC, Sceat commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
the action bar disappears on the client

2021-11-27 22:16 UTC, DeltaEvo commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
Ah crap, even with the dedicated action bar packet ?

2021-11-29 00:24 UTC, Sceat commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
the what ?

2021-11-29 08:20 UTC, DeltaEvo commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
There is another packet to send an action bar
https://wiki.vg/Protocol#Action_Bar maybe it will not do that with this one

2021-11-29 19:37 UTC, Sceat commented on src/context.js
> +  get_max_health: () => 40,
about the max_health i can now take it from the `types` (#234) but for the stats point i'm waiting your update on #330 to know how to get it

2021-11-29 19:47 UTC, Sceat commented on src/player/action_bar.js
> +        // might be costly :/
depends on how you implement the stats point computation

2021-11-29 20:45 UTC, Sceat commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
it still disapear with that packet

2021-11-29 20:49 UTC, Sceat commented on src/player/action_bar.js
> +    aiter(abortable(setInterval(2000))).forEach(() => {
also timings will only affect real titles

2021-11-29 20:56 UTC, Sceat commented on src/context.js
> +  get_max_health: () => 40,
see [`dd22a61` (#363)](https://github.com/aresrpg/aresrpg/pull/363/commits/dd22a61e680cb9feb5b98678bd26722a38249082)

2021-12-04 17:09 UTC, DeltaEvo approved these changes

2021-12-05 12:09 UTC, merged