Send Targeted Entity Life with a Boss Bar
aresrpg/aresrpg pull request #366
Opened 2021-11-24 23:37 UTC by Sceat

2021-11-27 22:31 UTC, DeltaEvo requested changes

2021-11-27 22:31 UTC, DeltaEvo commented on src/boss_bar.js
> +export const Actions = {
Can you keep the comments please ?

2021-11-27 22:31 UTC, DeltaEvo commented on src/player/boss_bar.js
> +const UUID_LENGTH = 36
`UUID_V4_LENGTH`

2021-11-27 22:31 UTC, DeltaEvo commented on src/player/boss_bar.js
> +    })
A LRU cache for that seems very overkill, I think a simple ringbuffer of 3 elements would do the job here like for the damange indicators

2021-11-27 22:31 UTC, DeltaEvo commented on src/player/boss_bar.js
> +      )
I don't think this makes a valid uuid, a valid uuid should have dashes in it like `b7084b42-51c0-4132-8bdc-b66a74e4b19d`

2021-11-29 00:25 UTC, Sceat commented on src/player/boss_bar.js
> +      )
but it works 😵

2021-11-29 08:06 UTC, DeltaEvo commented on src/player/boss_bar.js
> +      )
I will check the code of prismarine to see if it rrally works then, but I don't think we should rely on that

2021-11-29 21:08 UTC, Sceat commented on src/player/boss_bar.js
> +      )
we already rely on something like this for the `SERVER_UUID`

2021-11-29 21:31 UTC, DeltaEvo commented on src/player/boss_bar.js
> +      )
This doesn't mean it's a good thing, but yeah we migh change that one too

2021-11-30 00:01 UTC, Sceat commented on src/player/boss_bar.js
> +    })
😢

2021-12-01 00:00 UTC, Sceat commented on src/player/boss_bar.js
> +      )
prismarine seems to format those as Pakkit show me correct uuids

2021-12-04 17:05 UTC, DeltaEvo approved these changes

2021-12-04 17:08 UTC, merged