Fix player screen throw an error when any click is made
aresrpg/aresrpg pull request #367
Opened 2021-11-25 22:27 UTC by Sceat

✅ Closes: #365

2021-11-25 23:02 UTC, Sceat commented
@DeltaEvo i can't understand the pipeline 🤯

2021-11-27 22:32 UTC, DeltaEvo requested changes

2021-11-27 22:32 UTC, DeltaEvo commented on src/context.js
> +  // player_screen.observe(context)
You don't need to remove that

2021-11-27 22:32 UTC, DeltaEvo commented on src/context.js
> +  // }),
Remove it instead of comment it

2021-11-29 00:31 UTC, Sceat commented
resolved but what the heck is wrong with the pipeline 🤯

2021-11-29 08:03 UTC, DeltaEvo commented
What do you mean by pipeline ?

2021-11-29 09:49 UTC, Sceat commented
the CI

2021-11-30 21:00 UTC, DeltaEvo approved these changes

2021-11-30 21:46 UTC, merged