Send a Boss Bar to the Player
aresrpg/aresrpg pull request #38
Opened 2020-11-05 19:32 UTC by alan-drieux

2020-11-05 19:58 UTC, Sceat requested changes
Looking good :sparkles:, having a lot of different options you should use a unique provider object

```js
export default {
	Colors   : { PINK: 0, ... },
	Divisions: { ... },
	Types    : { ... },
	Actions  : { ... },
	display  : ({ state, options }) => {
		...
	}
}
```

i would even merge available options inside the parameter like

```js
display = ({ state, action, title, ... })
```

```js
import Bossbar from ''

Bossbar.display({
	action: Bossbar.Actions.ADD
})
```

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +export const colorBossBar = {
Prefer using snakecase on function and variables names

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +    const { client } = state
When you only take one property prefer destructuring directly in the parameters, with a fallback
```js
({ client } = {}, params)
```

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +    let { action, title, health, color, dividers, flags } = params
this is a `const`, we *almost* never use `let`

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +    if (action)
```suggestion
    if (!action)
```

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +        title: JSON.stringify(title),
you don't check for `title` presence, are you sure the packet accept `undefined` as a value ? you may want to fallback to an empty string

2020-11-05 19:58 UTC, Sceat commented on src/boss_bar.js
> +    const configBossBar = {
we usually call that `options`

2020-11-06 12:09 UTC, Sceat requested changes

2020-11-06 12:09 UTC, Sceat commented on src/boss_bar.js
> +        if (!action && action != 0)
`if (action === undefined)`

2020-11-06 12:09 UTC, Sceat commented on src/boss_bar.js
> +            flags: flags || 2
prefer using the nullish coascelling operator instead of `||` which is now a deprecated practice, in case you have a falsy value it will trigger your fallback and this may be unwanted

2020-11-06 12:09 UTC, Sceat commented on src/boss_bar.js
> + * @property {array<object>} extra - Optional
optionals in jsdoc are written `{string} [color]`

2020-11-06 12:32 UTC, DeltaEvo requested changes

2020-11-06 12:32 UTC, DeltaEvo commented on src/boss_bar.js
> +    Flags: { DRAKEN_SKY: 1, BOSS_BAR: 2, CREATE_FOG: 4 },
I know that @Sceat asked for this but can you change it to multiple names export, I prefer to let user choose if it want an object with all of this or do individual export ?
```js
export const Colors = { PINK: 0, ... }
export const Divisions = { ... }
export const Types = { ... }
export const Actions = { ... }
```

2020-11-06 12:32 UTC, DeltaEvo commented on src/boss_bar.js
> +    display({ state, options }) {
`display` seems to be too generic for me I whould prefer something like `write_bossbar`

2020-11-06 12:32 UTC, DeltaEvo commented on src/boss_bar.js
> +        if (!action && action != 0)
Why are you checking the action ? node-minecraft-protocol will do that himself

2020-11-06 12:32 UTC, DeltaEvo commented on src/boss_bar.js
> +            flags: flags || 2
What are theses default values ?
I don't think we need to have default values

2020-11-06 12:32 UTC, DeltaEvo commented on src/boss_bar.js
> +    display({ state, options }) {
`{ state, options }` make this into two arguments `state` and `options` and destructure them

2020-11-06 12:33 UTC, DeltaEvo commented on src/boss_bar.js
> + * @property {number} flags - DRAKEN_SKY: 1, BOSS_BAR: 2, CREATE_FOG: 4
`DRAKEN_SKY` => `DARKEN_SKY`

2020-11-06 17:11 UTC, Sceat commented on src/boss_bar.js
> +    display({ state, options }) {
why that, single arguments is far more functional

2020-11-06 17:32 UTC, DeltaEvo commented on src/boss_bar.js
> +    display({ state, options }) {
Can you explain why ?

2020-11-06 17:33 UTC, Sceat commented on src/boss_bar.js
> +    display({ state, options }) {
Explain first

2020-11-06 17:46 UTC, DeltaEvo commented on src/boss_bar.js
> +    display({ state, options }) {
Because I prefer to have the state as first argument and an action as second one, to be coherant with the rest of the codebase and to have the same style as our reducers that will have the signature `(state, action): next_sate` like redux reducers

2020-11-07 21:44 UTC, DeltaEvo commented on src/boss_bar.js
> +        title: JSON.stringify(title),
```suggestion
        title: title && JSON.stringify(title),
```

2020-11-07 22:11 UTC, DeltaEvo commented on src/boss_bar.js
> +        flags: flags
Use property shorthands http://es6-features.org/#PropertyShorthand

2020-11-14 17:42 UTC, DeltaEvo approved these changes

2020-11-14 17:43 UTC, merged