feat: Provide a enhanced readme
aresrpg/aresrpg pull request #39
Opened 2020-11-05 21:11 UTC by Sceat

2020-11-05 21:22 UTC, DeltaEvo requested changes

2020-11-05 21:22 UTC, DeltaEvo commented on README.md
> +  <img src="https://i.imgur.com/5doezIg.png" />
Keep the banner or upload this file to the repository

2020-11-05 21:23 UTC, DeltaEvo commented
Thanks for the changes this is much better :smile: 

Can you also rename your commit to Capitalize the first letter ?

2020-11-05 21:55 UTC, DeltaEvo requested changes
Last little thing can you merge/squash your two commits together ?

2020-11-06 11:56 UTC, Sceat commented
🤬

2020-11-06 19:29 UTC, DeltaEvo approved these changes

2020-11-07 00:41 UTC, merged