Implement death countdown
aresrpg/aresrpg pull request #426
Opened 2022-01-05 23:01 UTC by Sceat

2022-01-05 23:02 UTC, Sceat commented
need #402

2022-01-18 18:07 UTC, DeltaEvo requested changes

2022-01-18 18:07 UTC, DeltaEvo commented on src/player/respawn.js
> +          ).reduce(remaining => {
I think you can avoid using a custom signal with a https://github.com/tc39/proposal-iterator-helpers#takelimit

2022-01-19 14:13 UTC, Sceat commented on src/player/respawn.js
> +          ).reduce(remaining => {
yo that's clever

2022-01-20 07:15 UTC, DeltaEvo approved these changes

2022-01-20 09:54 UTC, merged