basic chat system + welcome message
aresrpg/aresrpg pull request #44
Opened 2020-11-08 16:53 UTC by Zekirax

2020-11-08 17:06 UTC, DeltaEvo requested changes

2020-11-08 17:06 UTC, DeltaEvo commented on src/chat.js
> +  const msg = 'Bienvenue ' + newClient.username + ' !'
And use template strings https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2020-11-08 17:06 UTC, DeltaEvo commented on src/index.js
> +      msg = '<' + client.username + '> ' + msg
Use the chat format https://wiki.vg/Chat
And use template strings https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2020-11-08 17:06 UTC, DeltaEvo commented on src/index.js
> +      msg = '<' + client.username + '> ' + msg
You also have a translation component for this `"chat.type.text": "<%s> %s"`

2020-11-08 19:29 UTC, DeltaEvo requested changes
Almost there :)
Remove the `master` file that you added and remove all theses newlines

2020-11-08 19:29 UTC, DeltaEvo commented on src/chat.js
> +export function send_chat_msg(server, json_msg, sender) {
Make a function with that signature `send_chat_msg({ server }, { message, sender })`

2020-11-08 19:29 UTC, DeltaEvo commented on src/index.js
> +    add_chat_listener(server, client)
Rename this to `chat` and only take `state` as argument (add the server to the state if needed)

2020-11-08 19:29 UTC, DeltaEvo commented on src/chat.js
> +export function send_chat_msg(server, json_msg, sender) {
And name this `write_chat_msg`

2020-11-08 21:35 UTC, Sceat commented on src/chat.js
> +export function send_chat_msg(server, json_msg, sender) {
you should indeed avoid using many arguments and prefer an object instead to prevent parameters ordering ambiguities, 2 parameters is somehow a limit

2020-11-10 16:12 UTC, DeltaEvo commented on src/chat.js
> +  const client = state.client
Destructure `state`

2020-11-10 21:00 UTC, DeltaEvo commented on src/chat.js
> +export function write_chat_msg(server, chat_message) {
Destructure `chat_message`

2020-11-10 21:01 UTC, DeltaEvo commented on src/chat.js
> +export function write_chat_msg(server, chat_message) {
And take `state` instead of server the function should look like this `write_chat_msg({ server }, { message, sender })`

2020-11-10 22:27 UTC, Zekirax commented on src/chat.js
> +export function write_chat_msg(server, chat_message) {
But why {server} and not just server, and why {message, sender} and not message, sender ?

2020-11-10 22:34 UTC, DeltaEvo commented on src/chat.js
> +export function write_chat_msg(server, chat_message) {
For the first one is just to keep the codebase style and be more modular for the future, the server come from the state so instead of just taking the server take the whole state and take the server from that so in the future if we make a refactor and rename server or need to use something else for example the current chunk we only need to refactor the function and not all the caller and the whole codebase do this

For the second argument it's to create named arguments in javascript so the order don't matter `write_chat_message(a, b, c)` is not the same as `write_chat_message(a, c, b)` but `write_chat_message(a, { b, c })` is the same as `write_chat_message(a, { c, b })` and about the name `sender` and `message` for the arguments it's to match the packet names

2020-11-11 09:57 UTC, Sceat requested changes

2020-11-11 09:57 UTC, Sceat commented on src/chat.js
> +}
A code style i'd like to see for these kind of behavior is to write a mapper and then apply it. That way when we read the code we don't have to pay attention at the loop, the brain can focus on the behavior alone

```suggestion
export function write_chat_msg(server, { json_msg, client: { uuid } }) {
  const options = {
    message: json_msg,
    position: 0, // use an enum here, 0 is a magic value
    sender: uuid,
  }
  const send_packet = client => client.write('chat', options)
  Object.values(server.clients).forEach(send_packet)
}
```

2020-11-11 09:57 UTC, Sceat commented on src/chat.js
> +  client.on('chat', function (packet) {
```suggestion
  client.on('chat', packet => {
```

2020-11-11 09:57 UTC, Sceat commented on src/chat.js
> +export function chat(state) {
this function name is a bit too simple, what does it do ? prefer using self-explaining names like `handle_chat` `initialize_chat` etc

2020-11-11 10:09 UTC, DeltaEvo commented on src/chat.js
> +}
Can you rename json_msg into message ?

2020-11-11 10:10 UTC, DeltaEvo commented on src/chat.js
> +export function chat(state) {
chat is fine for me

2020-11-11 22:17 UTC, DeltaEvo requested changes

2020-11-11 22:17 UTC, DeltaEvo commented on src/chat.js
> +export function chat(state) {
Destructure `state` inside the argument

2020-11-11 22:17 UTC, DeltaEvo commented on src/chat.js
> +export function write_chat_msg({ server, json_msg, client }) {
Make the function have this signature `write_chat_msg({ server }, { message, sender })`

2020-11-11 22:18 UTC, DeltaEvo commented
And also remove the empty `master` file that you pushed

2020-11-12 18:31 UTC, DeltaEvo requested changes
A last few things and you still have a empty `master`file in your branch, can your remove it please ?

2020-11-12 18:31 UTC, DeltaEvo commented on src/chat.js
> +  { json_msg, client: { uuid } }
Name json_msg message

2020-11-12 18:31 UTC, DeltaEvo commented on src/chat.js
> +export function chat({ state: { server, client } }) {
Take state as parameter directly instead of an object with state so { server, client } directly

2020-11-14 11:07 UTC, DeltaEvo approved these changes

2020-11-14 11:08 UTC, merged