Implement Teleportation stones
aresrpg/aresrpg pull request #45
Opened 2020-11-12 13:27 UTC by Vahelnir

TODO:
- [x] Spawn teleportation stones
- [x] Stones' display name
- [x] Open inventory when interacting with a teleportation stone
- [x] Use items representing each available teleportation stone
- [ ] Prevent any interaction with the inventory
- [x] Teleport to the corresponding teleportation stone when clicking on an item

2021-02-27 17:13 UTC, DeltaEvo requested changes
Looks good :+1: just some small changes

2021-02-27 17:13 UTC, DeltaEvo commented on src/teleporation_stones.js
> +function on_window_click({ world, client, position, get_state }) {
There is no position in the context

2021-02-27 17:13 UTC, DeltaEvo commented on src/teleporation_stones.js
> +            ...position,
Do you really need this ?

2021-02-27 17:26 UTC, Vahelnir commented on src/teleporation_stones.js
> +function on_window_click({ world, client, position, get_state }) {
Yep, probably a remnant of the first version of that code (that i didn't clean after all of the rebase).
I should get it from `get_state()`

2021-02-27 17:27 UTC, Vahelnir commented on src/teleporation_stones.js
> +            ...position,
I don't "need it". I did it that way so that the player can keep it's yaw and pitch (because at the beginnin g i didn't reset the yaw/pitch to 0).
It's obviously not mandatory and I can remove that part 🤷

2021-02-27 17:29 UTC, DeltaEvo commented on src/teleporation_stones.js
> +            ...position,
Yep ok, so we can keep the yaw and pitch of the player or set it to zero :thinking:

I let you choose :upside_down_face:

2021-02-27 17:30 UTC, Vahelnir commented on src/teleporation_stones.js
> +            ...position,
The yaw and pitch can be overridden by the `teleport_to` property of the teleportation_stone.json if needed. I think I can remove the use of the player position here.

2021-02-27 17:31 UTC, DeltaEvo approved these changes

2021-02-28 10:24 UTC, Sceat requested changes
Nice, the player should have his `unlocked stones` in his state so that he can't teleport to the undiscovered ones

2021-02-28 10:24 UTC, Sceat commented on src/teleporation_stones.js
> +    client.on('window_click', on_window_click(state))
those functions should appear before using them in the file

2021-02-28 10:24 UTC, Sceat commented on src/teleporation_stones.js
> +        // TODO: MAGIC NUMBERS EVERYWHERE
at least move them into constants at the top of the file :grimacing:

2021-02-28 10:24 UTC, Sceat commented on src/teleporation_stones.js
> +        length: 18,
you can compute the stones list into the length with some bounds ?

2021-02-28 10:26 UTC, DeltaEvo commented
> Nice, the player should have his unlocked stones in his state so that he can't teleport to the undiscovered ones

Yep :thumbups: I think after merging we can open an issue for that do implement it in a followup pull request

2021-07-27 18:08 UTC, DeltaEvo commented
Rebased in #230

2021-07-27 18:08 UTC, closed without merging