add %item% & %pos% links
aresrpg/aresrpg pull request #488
Opened 2022-07-09 10:53 UTC by SohKey

Added %pos% to share position in chat:
![image](https://user-images.githubusercontent.com/45180021/178102585-0aaaa28e-6680-49d7-b522-192b1e1a4a69.png)

Re-implemented %item% to share item in hand:

![image](https://user-images.githubusercontent.com/45180021/178102610-830808e9-5335-4cc2-891a-a36b73cf31d2.png)

code is probably ugly (i'm starting in nodejs) please give me advises :)

2022-07-09 13:12 UTC, Sceat requested changes
Thanks for the contribution! don't forget to run `npm run format` before pushing commits :)

There are some problems with the approach you used, i left a few comments and also rewrited the file, you can see in a comment below a cleaner implementation

2022-07-09 13:12 UTC, Sceat commented
```js
import nbt from 'prismarine-nbt'
import minecraftData from 'minecraft-data'

import { item_to_slot } from '../items.js'
import logger from '../logger.js'
import execute_command from '../commands/commands.js'
import { VERSION } from '../settings.js'
import { Formats, world_chat_msg } from '../chat.js'
import { World } from '../events.js'
import items from '../../data/items.json' assert { type: 'json' }

const mcData = minecraftData(VERSION)
const log = logger(import.meta)

function is_command_function(message) {
  return message.trimStart()[0] === '/'
}

function slot_to_chat({ nbtData, itemCount, itemId }) {
  const tag = nbt.simplify(nbtData)
  const { name } = mcData.items[itemId]
  const chat = {
    ...JSON.parse(tag.display.Name),
    hoverEvent: {
      action: 'show_item',
      contents: {
        id: name,
        itemCount,
        tag: JSON.stringify(tag),
      },
    },
  }
  return chat
}

export default {
  /** @type {import('../context.js').Observer} */
  observe({ client, get_state, world, dispatch }) {
    const chat_mapper = {
      '%item%': () => {
        const { held_slot_index, inventory } = get_state()
        const item = inventory[held_slot_index + 36] // For the player 0 is the first item in hotbar. But for the game the hotbat begin at 36.
        if (item) {
          const { type, count } = item
          return slot_to_chat(item_to_slot(items[type], count))
        }
      },
      '%item\\d%': word => {
        const slot_number = parseInt(word.match(/\d/)[0]) + 36 // same
        const { inventory } = get_state()
        const item = inventory[slot_number]
        if (item) {
          const { type, count } = item
          return slot_to_chat(item_to_slot(items[type], count))
        }
      },
      '%pos%': () => {
        const {
          position: { x, y },
        } = get_state()
        return { text: `[${x}, ${y}] `, ...Formats.INFO }
      },
    }

    client.on('chat', packet => {
      const { message } = packet
      const { nickname } = get_state()

      if (is_command_function(message)) {
        log.info({ sender: client.uuid, command: message }, 'Command')
        execute_command({ world, message, sender: client, get_state, dispatch })
        return
      } else {
        log.info({ sender: client.uuid, message }, 'Message')
      }

      world_chat_msg({
        world,
        message: [
          { text: `${nickname}: `, ...Formats.BASE, italic: false },
          ...message.split(' ').map(word => {
            for (const pattern in chat_mapper)
              if (word.match(pattern)) return chat_mapper[pattern](word)
            return { text: `${word} `, ...Formats.BASE, italic: false }
          }),
        ],
        client,
      })
    })
    const on_chat = options => client.write('chat', options)
    const on_private_message = ({ receiver_username, options }) => {
      if (receiver_username === client.username) client.write('chat', options)
    }

    world.events.on(World.CHAT, on_chat)
    world.events.on(World.PRIVATE_MESSAGE, on_private_message)

    client.once('end', () => {
      world.events.off(World.CHAT, on_chat)
      world.events.off(World.PRIVATE_MESSAGE, on_private_message)
    })
  },
}
```

2022-07-09 18:41 UTC, SohKey commented on src/player/chat.js
> +    text:"Position", color: 'gold',
I wanted to share the zone and on hover the coordonates appear : 
![image](https://user-images.githubusercontent.com/45180021/178118824-fcb37e42-aded-47cd-9a70-0c53aa7db600.png)

2022-07-09 18:43 UTC, SohKey commented on src/player/chat.js
> +              var posY = position["y"]
sorry ;( 
Im aware now x)

2022-07-09 18:43 UTC, SohKey commented
> Thanks for the contribution! don't forget to run `npm run format` before pushing commits :)
> 
> There are some problems with the approach you used (like having multiple pos and item in the same msg), i left a few comments and also **rewrited the file to show you a leaner implementation** _(unable to use `replaceAll` because of the `\d`)_
> 
> ```js
> import nbt from 'prismarine-nbt'
> import minecraftData from 'minecraft-data'
> 
> import { item_to_slot } from '../items.js'
> import logger from '../logger.js'
> import execute_command from '../commands/commands.js'
> import { VERSION } from '../settings.js'
> import { Formats, world_chat_msg } from '../chat.js'
> import { World } from '../events.js'
> import items from '../../data/items.json' assert { type: 'json' }
> 
> const mcData = minecraftData(VERSION)
> const log = logger(import.meta)
> 
> function is_command_function(message) {
>   return message.trimStart()[0] === '/'
> }
> 
> function slot_to_chat({ nbtData, itemCount, itemId }) {
>   const tag = nbt.simplify(nbtData)
>   const { name } = mcData.items[itemId]
>   const chat = {
>     ...JSON.parse(tag.display.Name),
>     hoverEvent: {
>       action: 'show_item',
>       contents: {
>         id: name,
>         itemCount,
>         tag: JSON.stringify(tag),
>       },
>     },
>   }
>   return chat
> }
> 
> export default {
>   /** @type {import('../context.js').Observer} */
>   observe({ client, get_state, world, dispatch }) {
>     const chat_mapper = {
>       '%item%': () => {
>         const { held_slot_index, inventory } = get_state()
>         const item = inventory[held_slot_index + 36] // For the player 0 is the first item in hotbar. But for the game the hotbat begin at 36.
>         if (item) {
>           const { type, count } = item
>           return slot_to_chat(item_to_slot(items[type], count))
>         }
>       },
>       '%item\\d%': word => {
>         const slot_number = parseInt(word.match(/\d/)[0]) + 36 // same
>         const { inventory } = get_state()
>         const item = inventory[slot_number]
>         if (item) {
>           const { type, count } = item
>           return slot_to_chat(item_to_slot(items[type], count))
>         }
>       },
>       '%pos%': () => {
>         const {
>           position: { x, y },
>         } = get_state()
>         return { text: `[${x}, ${y}] `, ...Formats.INFO }
>       },
>     }
> 
>     client.on('chat', packet => {
>       const { message } = packet
>       const { nickname } = get_state()
> 
>       if (is_command_function(message)) {
>         log.info({ sender: client.uuid, command: message }, 'Command')
>         execute_command({ world, message, sender: client, get_state, dispatch })
>         return
>       } else {
>         log.info({ sender: client.uuid, message }, 'Message')
>       }
> 
>       world_chat_msg({
>         world,
>         message: [
>           { text: `${nickname}: `, ...Formats.BASE, italic: false },
>           ...message.split(' ').map(word => {
>             for (const pattern in chat_mapper)
>               if (word.match(pattern)) return chat_mapper[pattern](word)
>             return { text: `${word} `, ...Formats.BASE, italic: false }
>           }),
>         ],
>         client,
>       })
>     })
>     const on_chat = options => client.write('chat', options)
>     const on_private_message = ({ receiver_username, options }) => {
>       if (receiver_username === client.username) client.write('chat', options)
>     }
> 
>     world.events.on(World.CHAT, on_chat)
>     world.events.on(World.PRIVATE_MESSAGE, on_private_message)
> 
>     client.once('end', () => {
>       world.events.off(World.CHAT, on_chat)
>       world.events.off(World.PRIVATE_MESSAGE, on_private_message)
>     })
>   },
> }
> ```

2022-07-09 20:50 UTC, SohKey commented
> Thanks for the contribution! don't forget to run `npm run format` before pushing commits :)
> 
> There are some problems with the approach you used (like having multiple pos and item in the same msg), i left a few comments and also **rewrited the file to show you a leaner implementation** _(unable to use `replaceAll` because of the `\d`)_
> 
> ```js
> import nbt from 'prismarine-nbt'
> import minecraftData from 'minecraft-data'
> 
> import { item_to_slot } from '../items.js'
> import logger from '../logger.js'
> import execute_command from '../commands/commands.js'
> import { VERSION } from '../settings.js'
> import { Formats, world_chat_msg } from '../chat.js'
> import { World } from '../events.js'
> import items from '../../data/items.json' assert { type: 'json' }
> 
> const mcData = minecraftData(VERSION)
> const log = logger(import.meta)
> 
> function is_command_function(message) {
>   return message.trimStart()[0] === '/'
> }
> 
> function slot_to_chat({ nbtData, itemCount, itemId }) {
>   const tag = nbt.simplify(nbtData)
>   const { name } = mcData.items[itemId]
>   const chat = {
>     ...JSON.parse(tag.display.Name),
>     hoverEvent: {
>       action: 'show_item',
>       contents: {
>         id: name,
>         itemCount,
>         tag: JSON.stringify(tag),
>       },
>     },
>   }
>   return chat
> }
> 
> export default {
>   /** @type {import('../context.js').Observer} */
>   observe({ client, get_state, world, dispatch }) {
>     const chat_mapper = {
>       '%item%': () => {
>         const { held_slot_index, inventory } = get_state()
>         const item = inventory[held_slot_index + 36] // For the player 0 is the first item in hotbar. But for the game the hotbat begin at 36.
>         if (item) {
>           const { type, count } = item
>           return slot_to_chat(item_to_slot(items[type], count))
>         }
>       },
>       '%item\\d%': word => {
>         const slot_number = parseInt(word.match(/\d/)[0]) + 36 // same
>         const { inventory } = get_state()
>         const item = inventory[slot_number]
>         if (item) {
>           const { type, count } = item
>           return slot_to_chat(item_to_slot(items[type], count))
>         }
>       },
>       '%pos%': () => {
>         const {
>           position: { x, y },
>         } = get_state()
>         return { text: `[${x}, ${y}] `, ...Formats.INFO }
>       },
>     }
> 
>     client.on('chat', packet => {
>       const { message } = packet
>       const { nickname } = get_state()
> 
>       if (is_command_function(message)) {
>         log.info({ sender: client.uuid, command: message }, 'Command')
>         execute_command({ world, message, sender: client, get_state, dispatch })
>         return
>       } else {
>         log.info({ sender: client.uuid, message }, 'Message')
>       }
> 
>       world_chat_msg({
>         world,
>         message: [
>           { text: `${nickname}: `, ...Formats.BASE, italic: false },
>           ...message.split(' ').map(word => {
>             for (const pattern in chat_mapper)
>               if (word.match(pattern)) return chat_mapper[pattern](word)
>             return { text: `${word} `, ...Formats.BASE, italic: false }
>           }),
>         ],
>         client,
>       })
>     })
>     const on_chat = options => client.write('chat', options)
>     const on_private_message = ({ receiver_username, options }) => {
>       if (receiver_username === client.username) client.write('chat', options)
>     }
> 
>     world.events.on(World.CHAT, on_chat)
>     world.events.on(World.PRIVATE_MESSAGE, on_private_message)
> 
>     client.once('end', () => {
>       world.events.off(World.CHAT, on_chat)
>       world.events.off(World.PRIVATE_MESSAGE, on_private_message)
>     })
>   },
> }
> ```

2022-07-09 21:03 UTC, Sceat commented on src/player/chat.js
> +    text:"Position", color: 'gold',
maybe a `%zone%` then

2022-07-10 00:35 UTC, Sceat requested changes

2022-07-10 00:35 UTC, Sceat commented on src/player/action_bar.js
> +      const { position } = get_state()
get_state doesn't need to be called 2 times

2022-07-10 00:35 UTC, Sceat commented on src/player/action_bar.js
> +        const { position } = get_state()
the state is already present line 76, `get_state` should only be used when there is no other way to access it

2022-07-10 00:35 UTC, Sceat commented on src/player/teleportation_stones.js
> +}
there already are usable distance function in `src/math.js`

2022-07-10 00:35 UTC, Sceat commented on src/player/teleportation_stones.js
> +  }
That function is ambiguous as it says closest_stone not closest_stones_names, it should return a single stone or have its name changed. But it's better to return a simple stone. (also wilderness is not a stone)

You don't need the world, just the stones array, also it's better to use an object argument, or in the case a signature as below

> A player can't be in 2 different zones btw

> the distance function comes from `src/math.js`

```suggestion
const PLAYER_ZONE_DISTANCE = 30

// note that a player at equal distance of 2 stones
// would be at the zone limit so it doesn't matter if we say one or the other
export function closest_stone(stones, { position }) {
  return stones.find(stone => distance(stone.position, position) <= PLAYER_ZONE_DISTANCE)
}
```

that function returns a stone or `undefined` so you can verify as
`const zone = closest_stone() ?? 'wilderness'`

2022-07-10 00:35 UTC, Sceat commented on src/player/chat.js
> +    text:`§6§nPosition:§r§a ${zone}`,
you have to use text components instead of mojang's magic char `§`

2022-07-10 00:35 UTC, Sceat commented on src/player/chat.js
> +    translate:"chat.type.text",
This is unneeded

2022-07-10 00:35 UTC, Sceat commented on src/player/chat.js
> +      value:`§dX: ${x} Y: ${y}`,
We should not show the exact position when a player simply wants to show the zone

2022-07-11 09:06 UTC, DeltaEvo commented on src/player/chat.js
> +            value: `X: ${Math.round(position.x)} Y: ${Math.round(position.y)}`,
I think here we want to show `X and Z` instead as `Y` is the height

2022-07-11 09:12 UTC, DeltaEvo commented on src/player/chat.js
> +        ],
I would prefer for us to keep the translating key (cc @Sceat) as this allows to not hardcode the format here and use the one that we put in the ressource pack

```suggestion
        message: {
          translate: 'chat.type.text',
          with: [
            {
              text: client.username,
            },
            message.split(' ').map(word => {
              for (const pattern in chat_mapper)
                if (word.match(pattern)) return chat_mapper[pattern](word)
              return { text: `${word} `, ...Formats.BASE, italic: false }
            }),
          ],
        },
```

2022-07-11 09:14 UTC, DeltaEvo commented on src/player/chat.js
> +            return { text: `${word} `, ...Formats.BASE, italic: false }
I think this implementation doesn't work as intended as no space is added if the word match, so I'm expecting for `Hello %item% World` to remove the space after the item.
Could you test that @SohKey

Also I'm not a big fan of the extra trailing space at the end

(cc @Sceat)

2022-07-11 09:15 UTC, DeltaEvo commented
@Sceat could you resolve the comments that you think are fixed ?

2022-07-11 12:36 UTC, SohKey commented on src/player/chat.js
> +            value: `X: ${Math.round(position.x)} Y: ${Math.round(position.y)}`,
Yes, i just checked and for me z was the height, i will change that

2022-07-11 12:40 UTC, SohKey commented on src/player/chat.js
> +            return { text: `${word} `, ...Formats.BASE, italic: false }
yep, you are right the bug is as you say

2022-07-11 16:24 UTC, SohKey reviewed
- Correction for %pos% y --> z
- Added suggered code
- Correction for player without item in hand trying to link item in chat
   -> Issue: The actual code dont allow to send a msg to prevent player
- Issue: player has to put space between %item% to link various items (%item1%%item2% return only %item1%)

2022-07-11 19:03 UTC, Sceat commented on src/player/chat.js
> +        ],
oh this is resource handled ? interesting

2022-07-11 19:05 UTC, Sceat commented on src/player/chat.js
> +            return { text: `${word} `, ...Formats.BASE, italic: false }
a space should be added to `slot_to_chat`

2022-07-11 19:15 UTC, DeltaEvo commented
I'm not sure to understand why it is not supposed to write that :thinking:

2022-07-11 19:16 UTC, Sceat commented
> I'm not sure to understand why it is not supposed to write that 🤔

%item1% %item2% is valid

2022-07-11 19:17 UTC, DeltaEvo commented
Yes and why `%item1%%item2%` is not ?

2022-07-18 18:09 UTC, DeltaEvo commented on src/player/chat.js
> +            }),
```suggestion
            message.split(new RegExp(`(${Object.keys(chat_mapper).join('|')})`).map(word => {
              for (const pattern in chat_mapper)
                if (
                  word.match(pattern) &&
                  chat_mapper[pattern](word) !== undefined
                )
                  return chat_mapper[pattern](word)
              return { text: word }
            }),
```

2022-07-18 18:10 UTC, DeltaEvo commented on src/player/chat.js
> +      '%item\\d%': word => {
```suggestion
      [/%item\d%/.source]: word => {
```

2022-07-18 18:59 UTC, DeltaEvo approved these changes

2022-07-18 19:01 UTC, DeltaEvo approved these changes

2022-07-18 19:03 UTC, merged