Added ladders & vine support
aresrpg/aresrpg pull request #525
Opened 2022-10-25 17:10 UTC by Gretorm

#377

2022-10-26 08:06 UTC, Sceat requested changes

2022-10-26 08:06 UTC, Sceat commented on src/player/tags.js
> +  return tagsObject
You are doing way too much unreadable computation here, if your goal is to construct a usable object, here is a simple approach

```js
const create = array => array.map(tagName => ({ tagName, entries: [] }))
const object = { blockTags: create(blockTags), ... }
```

2022-11-25 14:34 UTC, Sceat requested changes
Good effort but try to be as simple and minimal as possible, the only code needed for this PR is

## src/tags.js
> note that it should not be in `src/player/`
```js
// transforming all base tags to an object { tagName: [], ... }
// so that it's easier to insert/replace attributes
const to_object = tags =>
  tags.reduce((result, name) => ({ ...result, [name]: [] }), {})

export const blockTags = to_object([
  'minecraft:climbable',
  'minecraft:enderman_holdable',
  'minecraft:banners',
  'minecraft:soul_fire_base_blocks',
  'minecraft:campfires',
  'minecraft:infiniburn_nether',
  'minecraft:flower_pots',
  'minecraft:infiniburn_overworld',
  'minecraft:wooden_fences',
  'minecraft:piglin_repellents',
  'minecraft:wall_post_override',
  'minecraft:wooden_slabs',
  'minecraft:portals',
  'minecraft:small_flowers',
  'minecraft:bamboo_plantable_on',
  'minecraft:wooden_trapdoors',
  'minecraft:pressure_plates',
  'minecraft:jungle_logs',
  'minecraft:wooden_stairs',
  'minecraft:spruce_logs',
  'minecraft:signs',
  'minecraft:carpets',
  'minecraft:base_stone_overworld',
  'minecraft:wool',
  'minecraft:wooden_buttons',
  'minecraft:stairs',
  'minecraft:wither_summon_base_blocks',
  'minecraft:logs',
  'minecraft:stone_bricks',
  'minecraft:hoglin_repellents',
  'minecraft:fire',
  'minecraft:beehives',
  'minecraft:ice',
  'minecraft:base_stone_nether',
  'minecraft:dragon_immune',
  'minecraft:crops',
  'minecraft:wall_signs',
  'minecraft:slabs',
  'minecraft:valid_spawn',
  'minecraft:mushroom_grow_block',
  'minecraft:guarded_by_piglins',
  'minecraft:wooden_doors',
  'minecraft:warped_stems',
  'minecraft:standing_signs',
  'minecraft:infiniburn_end',
  'minecraft:trapdoors',
  'minecraft:crimson_stems',
  'minecraft:buttons',
  'minecraft:flowers',
  'minecraft:corals',
  'minecraft:prevent_mob_spawning_inside',
  'minecraft:wart_blocks',
  'minecraft:planks',
  'minecraft:soul_speed_blocks',
  'minecraft:dark_oak_logs',
  'minecraft:rails',
  'minecraft:coral_plants',
  'minecraft:non_flammable_wood',
  'minecraft:leaves',
  'minecraft:walls',
  'minecraft:coral_blocks',
  'minecraft:beacon_base_blocks',
  'minecraft:strider_warm_blocks',
  'minecraft:fence_gates',
  'minecraft:bee_growables',
  'minecraft:shulker_boxes',
  'minecraft:wooden_pressure_plates',
  'minecraft:wither_immune',
  'minecraft:acacia_logs',
  'minecraft:anvil',
  'minecraft:birch_logs',
  'minecraft:tall_flowers',
  'minecraft:wall_corals',
  'minecraft:underwater_bonemeals',
  'minecraft:stone_pressure_plates',
  'minecraft:impermeable',
  'minecraft:sand',
  'minecraft:nylium',
  'minecraft:gold_ores',
  'minecraft:logs_that_burn',
  'minecraft:fences',
  'minecraft:saplings',
  'minecraft:beds',
  'minecraft:oak_logs',
  'minecraft:unstable_bottom_center',
  'minecraft:doors',
])
export const itemTags = to_object([
  'minecraft:banners',
  'minecraft:soul_fire_base_blocks',
  'minecraft:stone_crafting_materials',
  'minecraft:wooden_fences',
  'minecraft:piglin_repellents',
  'minecraft:beacon_payment_items',
  'minecraft:wooden_slabs',
  'minecraft:small_flowers',
  'minecraft:wooden_trapdoors',
  'minecraft:jungle_logs',
  'minecraft:lectern_books',
  'minecraft:wooden_stairs',
  'minecraft:spruce_logs',
  'minecraft:signs',
  'minecraft:carpets',
  'minecraft:wool',
  'minecraft:wooden_buttons',
  'minecraft:stairs',
  'minecraft:fishes',
  'minecraft:logs',
  'minecraft:stone_bricks',
  'minecraft:creeper_drop_music_discs',
  'minecraft:arrows',
  'minecraft:slabs',
  'minecraft:wooden_doors',
  'minecraft:warped_stems',
  'minecraft:trapdoors',
  'minecraft:crimson_stems',
  'minecraft:buttons',
  'minecraft:flowers',
  'minecraft:stone_tool_materials',
  'minecraft:planks',
  'minecraft:boats',
  'minecraft:dark_oak_logs',
  'minecraft:rails',
  'minecraft:non_flammable_wood',
  'minecraft:leaves',
  'minecraft:walls',
  'minecraft:coals',
  'minecraft:wooden_pressure_plates',
  'minecraft:acacia_logs',
  'minecraft:anvil',
  'minecraft:piglin_loved',
  'minecraft:music_discs',
  'minecraft:birch_logs',
  'minecraft:tall_flowers',
  'minecraft:sand',
  'minecraft:gold_ores',
  'minecraft:logs_that_burn',
  'minecraft:fences',
  'minecraft:saplings',
  'minecraft:beds',
  'minecraft:oak_logs',
  'minecraft:doors',
])
export const fluidTags = to_object(['minecraft:lava', 'minecraft:water'])
export const entityTags = to_object([
  'minecraft:skeletons',
  'minecraft:raiders',
  'minecraft:arrows',
  'minecraft:beehive_inhabitors',
  'minecraft:impact_projectiles',
])

export const to_tag_array = tags =>
  Object.entries(tags).map(([tagName, entries]) => ({ tagName, entries }))
```

## src/player/login.js
```js
...
      client.write('tags', {
        blockTags: to_tag_array({
          ...blockTags,
          'minecraft:climbable': [ladder.id, vine.id],
        }),
        itemTags: to_tag_array(itemTags),
        fluidTags: to_tag_array(fluidTags),
        entityTags: to_tag_array(entityTags),
      })
...
```

2022-11-25 17:13 UTC, DeltaEvo commented
I would prefer that we go even simpler and avoid transforming them to much, so basically remove `to_object` and create constants for the tags

```js
const to_tag_array = (tags) =>
  Object.entries(tags).map(([tagName, entries]) => ({ tagName, entries }))

export const BLOCK_TAGS = to_tag_array({
  "minecraft:climbable": [ladder.id, vine.id],
  "minecraft:enderman_holdable": [],
  "minecraft:banners": [],
  "minecraft:soul_fire_base_blocks": [],
  "minecraft:campfires": [],
  "minecraft:infiniburn_nether": [],
  "minecraft:flower_pots": [],
  "minecraft:infiniburn_overworld": [],
  "minecraft:wooden_fences": [],
  "minecraft:piglin_repellents": [],
  "minecraft:wall_post_override": [],
  "minecraft:wooden_slabs": [],
  "minecraft:portals": [],
  "minecraft:small_flowers": [],
  "minecraft:bamboo_plantable_on": [],
  "minecraft:wooden_trapdoors": [],
  "minecraft:pressure_plates": [],
  "minecraft:jungle_logs": [],
  "minecraft:wooden_stairs": [],
  "minecraft:spruce_logs": [],
  "minecraft:signs": [],
  "minecraft:carpets": [],
  "minecraft:base_stone_overworld": [],
  "minecraft:wool": [],
  "minecraft:wooden_buttons": [],
  "minecraft:stairs": [],
  "minecraft:wither_summon_base_blocks": [],
  "minecraft:logs": [],
  "minecraft:stone_bricks": [],
  "minecraft:hoglin_repellents": [],
  "minecraft:fire": [],
  "minecraft:beehives": [],
  "minecraft:ice": [],
  "minecraft:base_stone_nether": [],
  "minecraft:dragon_immune": [],
  "minecraft:crops": [],
  "minecraft:wall_signs": [],
  "minecraft:slabs": [],
  "minecraft:valid_spawn": [],
  "minecraft:mushroom_grow_block": [],
  "minecraft:guarded_by_piglins": [],
  "minecraft:wooden_doors": [],
  "minecraft:warped_stems": [],
  "minecraft:standing_signs": [],
  "minecraft:infiniburn_end": [],
  "minecraft:trapdoors": [],
  "minecraft:crimson_stems": [],
  "minecraft:buttons": [],
  "minecraft:flowers": [],
  "minecraft:corals": [],
  "minecraft:prevent_mob_spawning_inside": [],
  "minecraft:wart_blocks": [],
  "minecraft:planks": [],
  "minecraft:soul_speed_blocks": [],
  "minecraft:dark_oak_logs": [],
  "minecraft:rails": [],
  "minecraft:coral_plants": [],
  "minecraft:non_flammable_wood": [],
  "minecraft:leaves": [],
  "minecraft:walls": [],
  "minecraft:coral_blocks": [],
  "minecraft:beacon_base_blocks": [],
  "minecraft:strider_warm_blocks": [],
  "minecraft:fence_gates": [],
  "minecraft:bee_growables": [],
  "minecraft:shulker_boxes": [],
  "minecraft:wooden_pressure_plates": [],
  "minecraft:wither_immune": [],
  "minecraft:acacia_logs": [],
  "minecraft:anvil": [],
  "minecraft:birch_logs": [],
  "minecraft:tall_flowers": [],
  "minecraft:wall_corals": [],
  "minecraft:underwater_bonemeals": [],
  "minecraft:stone_pressure_plates": [],
  "minecraft:impermeable": [],
  "minecraft:sand": [],
  "minecraft:nylium": [],
  "minecraft:gold_ores": [],
  "minecraft:logs_that_burn": [],
  "minecraft:fences": [],
  "minecraft:saplings": [],
  "minecraft:beds": [],
  "minecraft:oak_logs": [],
  "minecraft:unstable_bottom_center": [],
  "minecraft:doors": [],
})

export const ITEM_TAGS = to_tag_array({
  "minecraft:banners": [],
  "minecraft:soul_fire_base_blocks": [],
  "minecraft:stone_crafting_materials": [],
  "minecraft:wooden_fences": [],
  "minecraft:piglin_repellents": [],
  "minecraft:beacon_payment_items": [],
  "minecraft:wooden_slabs": [],
  "minecraft:small_flowers": [],
  "minecraft:wooden_trapdoors": [],
  "minecraft:jungle_logs": [],
  "minecraft:lectern_books": [],
  "minecraft:wooden_stairs": [],
  "minecraft:spruce_logs": [],
  "minecraft:signs": [],
  "minecraft:carpets": [],
  "minecraft:wool": [],
  "minecraft:wooden_buttons": [],
  "minecraft:stairs": [],
  "minecraft:fishes": [],
  "minecraft:logs": [],
  "minecraft:stone_bricks": [],
  "minecraft:creeper_drop_music_discs": [],
  "minecraft:arrows": [],
  "minecraft:slabs": [],
  "minecraft:wooden_doors": [],
  "minecraft:warped_stems": [],
  "minecraft:trapdoors": [],
  "minecraft:crimson_stems": [],
  "minecraft:buttons": [],
  "minecraft:flowers": [],
  "minecraft:stone_tool_materials": [],
  "minecraft:planks": [],
  "minecraft:boats": [],
  "minecraft:dark_oak_logs": [],
  "minecraft:rails": [],
  "minecraft:non_flammable_wood": [],
  "minecraft:leaves": [],
  "minecraft:walls": [],
  "minecraft:coals": [],
  "minecraft:wooden_pressure_plates": [],
  "minecraft:acacia_logs": [],
  "minecraft:anvil": [],
  "minecraft:piglin_loved": [],
  "minecraft:music_discs": [],
  "minecraft:birch_logs": [],
  "minecraft:tall_flowers": [],
  "minecraft:sand": [],
  "minecraft:gold_ores": [],
  "minecraft:logs_that_burn": [],
  "minecraft:fences": [],
  "minecraft:saplings": [],
  "minecraft:beds": [],
  "minecraft:oak_logs": [],
  "minecraft:doors": [],
})

export const FLUID_TAGS = to_tag_array({
  "minecraft:lava": [],
  "minecraft:water": [],
})

export const ENTITY_TAGS = to_tag_array({
  "minecraft:skeletons": [],
  "minecraft:raiders": [],
  "minecraft:arrows": [],
  "minecraft:beehive_inhabitors": [],
  "minecraft:impact_projectiles": [],
})
```
```

2023-01-19 16:03 UTC, Sceat approved these changes

2023-01-19 16:03 UTC, merged