Toufoumaster/archery
aresrpg/aresrpg pull request #545
Opened 2022-11-22 23:21 UTC by ToufouMaster

Need a lot of rework, still a draft

2022-11-24 15:12 UTC, ToufouMaster commented
i'm not gonna format the code is prettier this way

2022-11-24 16:11 UTC, DeltaEvo commented
The point of having of style guide is to stick to it :)
So format your code :)

2022-11-24 16:14 UTC, ToufouMaster commented
it just add a line where there is no need to and make the code ugly, if you really want i'll do it

2022-11-25 12:33 UTC, Sceat commented
please don't request reviews for drafts

2022-11-25 18:18 UTC, ToufouMaster commented
it is not a draft anymore i formated the code

2022-11-27 17:23 UTC, Sceat requested changes
You have an excellent motivation but unfortunately this feature doesn't even work properly, the code logic is messy and you lack important concepts of the language. Most of the `reduce` body is unreadable and mix multiple different logic. Here is a review mainly on codestyle for you to learn but not even on the core, I suggest you try to handle easier feature as there isn't much to save from this one (in my opinion)

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +          })
you are using an async callback to assign values inside a sync reducer, this will result in mutating your variables at unpredictable moments and also destroying all life form on earth, avoid doing that or i call the police. Why even creating 3 variables ??

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +          let t = 0
`t` ? what is `t`, please use descriptive variables names

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +                  })
this has nothing to do with shooting arrows

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +                  })
may look cool to let arrows in the mob's body for some time

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +    })
handling mob visibility has nothing to do with archery

2022-11-27 17:23 UTC, Sceat commented on src/player/archery.js
> +        const state = get_state()
please avoid duplicated calls (the state)

2022-11-27 17:41 UTC, ToufouMaster commented on src/player/archery.js
> +        const state = get_state()
woops.

2022-11-28 12:58 UTC, ToufouMaster commented on src/player/archery.js
> +          let t = 0
forgot to remove... Whoops

2022-11-28 13:00 UTC, ToufouMaster commented on src/player/archery.js
> +                  })
where can i check for a arrow to collide a specific block outside of this function then?

2022-11-28 13:02 UTC, ToufouMaster commented on src/player/archery.js
> +    })
delta told me to use this to get every mob the player can see, it avoid me to check for EVERY possible mobs.

2022-11-28 13:02 UTC, ToufouMaster commented on src/player/archery.js
> +          })
> Why even creating 3 variables ??

ah,yes that's completely stupid, apart from that i can't call get_path_collision otherwise, or maybe in the reduce

2022-12-27 16:34 UTC, Sceat commented
Not usable & abandonned https://github.com/aresrpg/aresrpg/pull/545#pullrequestreview-1195005695

2022-12-27 16:34 UTC, closed without merging