Add basic scoreboard system with animations
aresrpg/aresrpg pull request #55
Opened 2020-11-18 22:35 UTC by Upd4ting

2020-11-22 11:21 UTC, DeltaEvo requested changes

2020-11-22 11:21 UTC, DeltaEvo commented on src/index.js
> +import { init_scoreboard } from './scoreboard/init_scoreboard.js'
`init_` seems to not add any meaning, `scoreboard` seems like a good name

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +}
We should not use theses magic color values, instead use the `color` property inside the https://wiki.vg/Chat Component, it's more readable, and it's future proof for example you can have `rgb` colors inside this property

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/init_scoreboard.js
> +    flush_sideline({ client })
I think this should be done with online one `send_sideline` function

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/init_scoreboard.js
> +    )
I think this should be done with only one `send_sidebar` function

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/scoreboard.js
> +}
Do you really need a function for that ?

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/scoreboard.js
> +}
Do you really need a function for that

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/scoreboard.js
> +}
Do you really need a function for that ?

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/sidebar.js
> +const clientTitleMap = new Map()
`TODO: should not exist :upside_down_face:`, you should not have global state like that
I think your issue here is that your breaking the sidebar into multiple function calls
Here for me you should have only one function
`update_sidebar` that take the old sidebar and the new sidebar and does what is needed to create/update/delete it

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/sideline.js
> +const clientBufferMap = new Map()
Same as `sidebar`

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +const clientAnimationMap = new Map()
This should not be needed, you should not break the logic into multiple function and use a global state, just make a function that create + start the animation and that return a function to cancel it like
```js
function start_animation(...) {
	const id = setInterval(...)
    return {
        cancel() { clearInterval(id) }
    }
}
```

2020-11-22 11:21 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +    : [animation.effect]
Simplify this make animation.effet to always be an array

2020-11-22 11:24 UTC, DeltaEvo requested changes
There is too much functions too call to use this, I think we should have only one function to create and send a sidebar scoreboard/sideline scoreboard/an animation
The animation code seems nice to use but the implementation is too complex for me, but first we should simplify the interface before the implementation

2020-11-22 14:32 UTC, Upd4ting commented on src/scoreboard/animations.js
> +}
At the beginning I wanted to use the chat component but then I saw that the scoreboard title handle chat component but not scoreboard line. As I wanted to make the animation for both line and title, I used these magic color values.

I can handle the different cases and let us use chat component only for the title, but it makes the implementation of animation more complex.

2020-11-22 16:42 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +}
I looked at minecraft code and indead it dosen't parse a component for this but it parse a chat component for the team prefix and suffix
We can hack something with the teams but I don't like this idea
But I think we can just make a function that transform a chat component into a string and throw an Error if it's not possible

2020-11-22 16:58 UTC, Upd4ting commented on src/scoreboard/animations.js
> +}
So the scoreboard interface will take a chat component and will convert that to a string for internal use?

2020-11-22 19:34 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +}
Yes, but for the magic values you will add them into a list or an enum so they will not be magic values anymore :)

2020-11-22 19:36 UTC, Upd4ting commented on src/scoreboard/animations.js
> +}
Perfect 👍

2020-12-04 23:26 UTC, DeltaEvo requested changes
Much better :+1: I will do a review of the animation system tomorrow

2020-12-04 23:26 UTC, DeltaEvo commented on src/scoreboard/sidebar.js
> +  }
```suggestion
  if (last.title !== next.title) {
    const name = client.username
    
  	if (next.title === undefined) {
  	  client.write('scoreboard_objective', { name, action: ObjectiveActions.REMOVE })
  	} else {
  	  const displayText = JSON.stringify(next.title)
  	  const type = Types.INTEGER
  	  
  	  if (last.title === undefined) {
  	      client.write('scoreboard_objective', { name, displayText, type, action: ObjectiveActions.CREATE })
  	      client.write('scoreboard_display_objective', {
            position: Positions.SIDEBAR,
            name,
          })
  	  } else
  	    client.write('scoreboard_objective', { name, displayText, type, action: ObjectiveActions.UPDATE })
  	}
  }
```

2020-12-04 23:26 UTC, DeltaEvo commented on src/scoreboard/sidebar.js
> +      !lastLines.find(
Use `some` instead of find https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/some

2020-12-04 23:26 UTC, DeltaEvo commented on src/scoreboard/sidebar.js
> +    return !sameLine || sameLine.text != item.text
```suggestion
    return sameLine?.text !== item.text ?? true
```

2020-12-04 23:26 UTC, DeltaEvo commented on src/scoreboard/util.js
> +}
```suggestion
const to_array = value => Array.isArray(value) ? value : [value]

export function chat_to_text(chat) {
  return to_array(chat).map(part => {
  	const modifiers = [
  	  ChatColor[part.color?.toUpperCase()] ?? '',
  	  part.obfuscated ? ChatColor.OBFUSCATED : '',
  	  part.bold ? ChatColor.BOLD : '',
  	  part.strikethrough ? ChatColor.STRIKETHROUGH : '',
      part.underline ? ChatColor.UNDERLINE : '',
      part.italic ? ChatColor.ITALIC : ''
  	]
  	
  	const extra = part.extra ? chat_to_text(part.extra) : ''
  	
  	return `${modifiers.join('')}${part.text}${extra}${ChatColor.RESET}`
  }).join('')
}
```

2020-12-04 23:26 UTC, DeltaEvo commented on src/scoreboard/enums.js
> +    color === '§o',
I think we should move this outside of this object because it will be in the ways if we use Object.entries on this object to get all chat colors for example

2020-12-10 21:33 UTC, DeltaEvo commented
For the animations code I think we can simplify it with this points:
-  I don't think we need a `start` function, you can just start the animation when we create it
-  I think it would be easier to just create all the frames an cycles through them for example
```js
```

2020-12-27 15:05 UTC, DeltaEvo commented on src/scoreboard/animations.js
> +        })
I think this can be simplified if you keep the chat components, so you don't need to care about colors inside the text
What I'm thinking is implementing a `split_chat_component` function
```js
split_chat_component({ text: 'hello', color: 'red' }, '')
=> [{ text: 'h', color: 'red' }, { text: 'e', color: 'red' }, ...]
```
And an `optimize_chat_component` that regroup the split chat component

2021-02-12 09:09 UTC, Sceat commented
@Upd4ting from what i see on the reviews you may be interested in deep diving into [pure programming concepts](https://www.freecodecamp.org/news/functional-programming-principles-in-javascript-1b8fc6c3563f/) :+1:

2021-02-14 07:06 UTC, Upd4ting commented
@Sceat yeah thanks for the reading :)

2021-08-21 22:39 UTC, Sceat requested changes
I propose that you move your animation system on top of the leaner scoreboard system (once https://github.com/aresrpg/aresrpg/pull/274 is merged)

2021-10-01 21:51 UTC, closed without merging