Use a submodule to access `items` and `entities`
aresrpg/aresrpg pull request #552
Opened 2022-11-30 10:08 UTC by Sceat

#551 
allowing us to have private submodules with proprietary data

2022-12-04 18:16 UTC, DeltaEvo commented on .gitmodules
> +	url = git@github.com:aresrpg/ares-data.git
nit: why not name it `data` ?
aresrpg/data.git ?

2022-12-04 18:21 UTC, DeltaEvo requested changes

2022-12-04 18:21 UTC, DeltaEvo commented on .gitmodules
> +	url = git@github.com:aresrpg/ares-data.git
```suggestion
	url = ../../aresrpg/ares-data.git
```

2022-12-04 18:24 UTC, DeltaEvo commented on README.md
> +```
```suggestion
```
git -C data remote add private git@github.com:aresrpg/ares-data-closed.git
git -C data checkout private/main
```
```

2022-12-04 18:24 UTC, DeltaEvo commented on README.md
> +git restore .gitmodules
```suggestion
git -C data remote add private git@github.com:aresrpg/ares-data-closed.git
git -C data checkout private/main
```

2022-12-04 18:38 UTC, Sceat commented on .gitmodules
> +	url = git@github.com:aresrpg/ares-data.git
Was about to but since i prefixed each new repo with `ares-` the choice of either will impact all of them, I'll think about that

2022-12-04 18:39 UTC, Sceat commented on .gitmodules
> +	url = git@github.com:aresrpg/ares-data.git
hum what's the reason for the relative path ?

2022-12-06 04:15 UTC, DeltaEvo commented on .gitmodules
> +	url = git@github.com:aresrpg/ares-data.git
This permit to use the same protocol as the parent repository,
So if the ares repo was cloned with: 
- `https://github.com/aresrpg/aresrpg.git` the url used will be `https://github.com/aresrpg/ares-data.git`
- `git@github.com:aresrpg/aresrpg.git` the url used will be `git@github.com:aresrpg/ares-data.git`

2022-12-06 06:06 UTC, DeltaEvo approved these changes

2022-12-06 06:08 UTC, merged