Commit without interactable_object.json
aresrpg/aresrpg pull request #570
Opened 2022-12-02 10:52 UTC by KalvinVilla

I don't know how commit world/floor1/interactable_object.json because is in submodule i will try later but for your information the content of this json is : 

```
[
    {
        "type": 222,
        "permit": "allow",
        "location": {
            "x": 459,
            "y": 170,
            "z": 663
          }
    },
    {
        "type": 161,
        "permit": "deny",
        "location": {
            "x": 453,
            "y": 167,
            "z": 665
          },
        "custom_message": "``This door seem closed, you maybe need a key``"
    },
    {
        "type": 222,
        "location": "*",
        "permit": "deny"
    }
]
```

2022-12-03 03:42 UTC, Sceat commented
What is the goal of this PR ? the name isn't descriptive

2022-12-04 18:04 UTC, KalvinVilla commented
ohh i forgetten
it's for the issue 443 (Some trapdors should be openable) i just added some feature for other block

2022-12-04 18:41 UTC, Sceat commented
> ohh i forgetten it's for the issue 443 (Some trapdors should be openable) i just added some feature for other block

please update the PR name accordingly and link any related issue

2022-12-05 18:27 UTC, Sceat requested changes
https://github.com/aresrpg/aresrpg/pull/570#issuecomment-1336487902

2022-12-08 17:16 UTC, Sceat commented
Let's see if we can synchronize the work in a single file along with https://github.com/aresrpg/aresrpg/pull/572

2022-12-11 14:26 UTC, SohKey requested changes
you should use more object destructuring and make your code more relevant to avoid side effects and make your code more readable. 
I will also request changes on the json PR aresrpg/floor1#5

2022-12-11 14:26 UTC, SohKey commented on src/player/interactable_object.js
> +            }
uses destructuring rather than fetching the property each time
`const {  custom_message, location } = interact_object`

2022-12-11 14:26 UTC, SohKey commented on src/player/interactable_object.js
> +}
here is a corrected version of the code
```suggestion
import { client_chat_msg } from '../chat.js'
import { get_block } from '../chunk.js'
import util from 'util'

const interactable_types = {
  trap: 222,
  door: 161
}

const door_state = {
  upper: 3576,
  bottom: 3584
}

function update_door (position) {
  const { x, y, z } = position
  const upper_location = {
    x,
    y: y + 1,
    z
  }

  const upper = { 
    location: upper_location,
    type: door_state.upper,
  }
  const bottom = {
    location: position,
    type: door_state.bottom,
  }
  
  return [upper, bottom]
}

/**
 * This function permit to allow or deny some interaction with specific block
 * Block interaction : world/{floor}/interactable_object.json
 * |   id   |   blockname   |
 * |  250   |  fence gate   |
 * |  222   |  trap door    |
 * |  161   |  door         |
 */
export default {
  /** @type {import('../context.js').Observer} */
  observe(context) {
    const { client, world } = context
    client.on('block_place', async ({ location }) => {
      const block = await get_block(world, location)

      const handle_interactable = async ({ allow, position, message, type }) => {
        if (!allow) {
          client_chat_msg({ client, message })

          if (type === interactable_types.door) {
            update_door(position).forEach((block) => {
              client.write('block_change', block)
            })     
          } else {
            client.write('block_change', {
              location: position,
              type: block.stateId,
            })
          }
        }
      }

      const interacted_object = world.interactable_object.find((payload) => {
        const { position } = payload

        if(block.type === interactable_types.door) { //check if the upper block is interacted
          const { x, y, z } = position
          const upper_door = {
            x,
            y: y + 1,
            z
          }

          if (util.isDeepStrictEqual(upper_door, location)) return payload
        }
        
        if (util.isDeepStrictEqual(position, location)) return payload
      })

      if (interacted_object) handle_interactable(interacted_object)
    })
  },
}
```

2022-12-11 17:48 UTC, Sceat commented on src/player/interactable_object.js
> +      let tag = 0
It's not forbidden there may be specific case where it's useful **BUT** peoples using `let` are usually banned before they can find such cases

2022-12-11 17:50 UTC, Sceat commented
Also the branch is not up to date

2022-12-12 07:33 UTC, KalvinVilla commented on src/player/interactable_object.js
> +              loc === '*')
Yep i know i was my first try to see if it's possible to cancel 2 block for door, but I didn’t have time to change it

2022-12-12 07:39 UTC, KalvinVilla commented on src/player/interactable_object.js
> +}
Thanks,
Like @Sceat said i think we will change a little bit this code to add other object like belll (with sound function ...)

2022-12-27 16:32 UTC, Sceat commented
forget about https://github.com/aresrpg/aresrpg/pull/570#issuecomment-1343042855 as #572 has been merged

2023-01-02 17:58 UTC, KalvinVilla commented
So i add sohkey code and made some changement 

Now the code is cleaner but it remove the function of specify * to specific any location in interactable_block.json
I don't know how you will use interact block in the new map,i think u wan't that every door is openable by default and every trapdoor isn't,

So i ask himself if we configure the default behavior in json like a do in first 
```
    {
        "type": 222,
        "position": "*"
    },
```

 or if we direcly set in js

2023-01-04 14:56 UTC, KalvinVilla commented
I try some changement to pass lint test but don't work, maybe need to first merge pr on floor1 before,
So i'm waiting your comment about this code

2023-01-04 15:31 UTC, Sceat requested changes
The commit history is not clean 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/11330271/210590356-c10396ef-da23-4b66-831f-5c2729bfcdfc.png">

Also you need to update the world submodule to access your changes, (it also has to be merged first)

2023-01-04 15:47 UTC, closed without merging