Add emotes to chat
aresrpg/aresrpg pull request #571
Opened 2022-12-03 10:15 UTC by SohKey

![image](https://user-images.githubusercontent.com/45180021/205435662-3371972d-c7ca-4bcf-bde6-39c04d313e3d.png)

- add emotes to chat mapper
- display rank before name (preview)

_Big tanks to Watich for lending me an account (what a bro)_

2022-12-04 05:20 UTC, Sceat requested changes
## About `data/emotes.json`
Take a look at `aresrpg/ares-data` it is a new submodule where these have been moved, it is yet to be reviewed by @DeltaEvo but if it's merged the correct place will be in `aresrpg/ares-data-closed`

2022-12-04 05:20 UTC, Sceat commented on data/emotes.json
> +  "providers": [
why do you need that additional nesting ?

2022-12-04 05:20 UTC, Sceat commented on src/player/chat.js
> +    })
The thinking process of creating something in order to fill it right after is imperative programming, in functionnal you would

```js
const emotes_mapper = emotes.providers
	.map(...)
	.reduce(...)
```

2022-12-04 05:20 UTC, Sceat commented on src/player/chat.js
> +    }
there was previously a nice flat mapper, now it's kinda hidden. Prefer appending your feature to the existing structure instead of moving it.

```
const chat_mapper = {
	'%pos%': () ... etc,
	...emotes.reduce(to_chat_map)
}
```

2022-12-04 05:20 UTC, Sceat commented on src/player/chat.js
> +                }
this is not a useful addition

2022-12-04 05:20 UTC, Sceat commented on src/player/chat.js
> +            },
I think the `chat.type.text` was important @DeltaEvo , also are you sure about that piece of code ? `' >> '` seem a big change maybe not the most good looking one

2022-12-04 11:21 UTC, SohKey commented on data/emotes.json
> +  "providers": [
`data/emotes.json` is the same file that is in the resource pack, the `"providers"` is required by minecraft.

2022-12-04 11:32 UTC, SohKey commented on src/player/chat.js
> +            },
I took it off because it's ugly in the game, Delta also told me it was important but not why. I now that `' >> '` is not looking good but i dont know how to do it better

2022-12-04 12:11 UTC, Sceat commented on data/emotes.json
> +  "providers": [
hum then this should be in the resourcepack repo ? let's discuss this on discord with @DeltaEvo and create an issue about it as we may have 2 ressourcepack repo very soon

2022-12-04 18:28 UTC, DeltaEvo commented on src/player/chat.js
> +            },
The usage of the translation key is that this is something that we can control from the resource pack and this is the standard minecraft key for the chat format so it provides and extension point for resource packs.

If we want to change it for AresRPG we can do that by updating inside the resource pack lang file https://gist.github.com/DeltaEvo/fe3143497b6422b718dcb68d3744171a#file-en_us-json-L378

2022-12-04 18:33 UTC, DeltaEvo commented on data/emotes.json
> +      "chars": [""]
We should create translation keys for the client like `aresrpg.emoji.ban` to not need to have that in this repo and only keep a list of emotes inside the `data` repository or just convert every :name: into a translation key, but I'm not sure what the client will do with that

2022-12-04 18:33 UTC, DeltaEvo commented on src/player/chat.js
> +            },
And further by re looking at wiki.vh, I remember with it's important, it's because this translation key is changed when the text is passed into the narrator which change the "style" formatting into text
```json
  "chat.type.text": "<%s> %s",
  "chat.type.text.narrate": "%s says %s",
```

> As a special case, if the translation key is chat.type.text, it will be changed to > chat.type.text.narrate when passed to narrator (although it will remain as
> chat.type.text in chat). 

https://wiki.vg/Chat#Translation_component

2022-12-04 18:34 UTC, DeltaEvo commented on src/player/chat.js
> +    const emoteFormated = emotes.providers.map(emote => {
nit: `emoteFormatted`

2022-12-04 18:37 UTC, DeltaEvo commented on data/emotes.json
> +{
Could you make a PR to the resource pack repository with this file ?

2022-12-13 01:16 UTC, SohKey commented
Bug: bad font when a none existing emote

2022-12-18 12:37 UTC, Sceat approved these changes

2022-12-18 12:37 UTC, Sceat commented
please rebase your branch

2022-12-26 20:28 UTC, SohKey commented
we have to add the emote json into the data submodules

2022-12-26 20:35 UTC, SohKey commented
Also this PR require merging:
- #aresrpg/data#3
- #aresrpg/ressourcepacks#7

2023-01-02 21:25 UTC, DeltaEvo requested changes

2023-01-02 21:25 UTC, DeltaEvo commented on src/player/chat.js
> +      [/:.*:/.source]: emote => emote_to_chat(emote.match(/.*/)[0]), // all emotes name are between ":"
```suggestion
      [/:.*:/.source]: emote_to_chat, // all emotes name are between ":"
```

2023-01-02 21:25 UTC, DeltaEvo commented on src/player/chat.js
> +  const emote_name = `${emote.split(':')[1]}`
```suggestion
  const emote_name = emote.slice(1, -1)
```

2023-01-04 12:57 UTC, SohKey commented
/merge

2023-01-05 16:55 UTC, Sceat commented
lol nice try hard 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/11330271/210836482-35ef0fec-7f5e-46cc-9dbd-f0a6ea74a67f.png">

but the 4th commit is still not [conventional](https://www.conventionalcommits.org/en/v1.0.0/)

2023-01-05 16:55 UTC, Sceat requested changes
https://github.com/aresrpg/aresrpg/pull/571#issuecomment-1372473817

2023-01-17 03:32 UTC, Sceat approved these changes

2023-01-17 03:32 UTC, Sceat commented
/merge

2023-01-17 03:33 UTC, merged