Handle right click on a bell
aresrpg/aresrpg pull request #572
Opened 2022-12-05 17:31 UTC by Arkobalt

My first PR ever, don't really know how to structure it.
The feature is quite simple so i dont really need to explain it, i guess.

2022-12-05 18:34 UTC, Sceat requested changes
Thank for contributing to AresRPG !

About your PR, you have a huge code duplication, you could simply
```js
client.write('block_action', {
    location,
    byte1: 1,
    byte2: direction,
    blockId: 677,
  })
  play_sound({
    client,
    sound: 'block.bell.use',
    category: CATEGORY.AMBIENT,
    ...location,
  })
```

I guess creating a file just for the bells are fine @DeltaEvo ? but maybe it should be in a more generic world entity files ? like trapdoors etc (cc @KalvinVilla)

2022-12-05 18:34 UTC, Sceat commented on src/player/bells.js
> +              blockId: 677,
those 3 values are magic numbers

2022-12-05 18:34 UTC, Sceat commented on src/context.js
> +  player_bells.observe(context) // fezrhnjhifhbredjihebghfrvdihje
`fezrhnjhifhbredjihebghfrvdihje` ?

2022-12-05 19:55 UTC, Arkobalt commented on src/player/bells.js
> +              blockId: 677,
I didn't think about it x).
The slight difference with this version is that the bell ring (sound) even when there is no animation (when rang from top or bottom).
I son't know the exact details of what was required but maybe we'll need to add another condition for sound if done this way.

2022-12-06 08:01 UTC, Arkobalt commented on src/context.js
> +  player_bells.observe(context) // fezrhnjhifhbredjihebghfrvdihje
It took me a day to realise that this was about the comment.
It's fixed.

2022-12-06 08:09 UTC, Sceat requested changes

2022-12-06 08:09 UTC, Sceat commented on src/player/bells.js
> +          z: location.z,
```suggestion
          ...location
```

2022-12-06 08:19 UTC, Arkobalt commented on src/player/bells.js
> +          blockId: 677, // bell id
oh, i see, i'll do that now

2022-12-08 17:07 UTC, Sceat commented
Seems good, let's now wait for @DeltaEvo opinion on https://github.com/aresrpg/aresrpg/pull/572#pullrequestreview-1205052568

2022-12-20 07:35 UTC, Arkobalt commented
My last commit was helpfull for test but may cause probleme because the mobs.json file from floor1 when starting the server. I dont know how without requesting a pull on floor1 but modifications on mobs.json should be discarded or the last commit should be ignored.

2022-12-20 13:26 UTC, Sceat approved these changes

2022-12-20 13:27 UTC, merged