Add support for integration tests
aresrpg/aresrpg pull request #585
Opened 2022-12-22 16:33 UTC by Sceat

2022-12-22 16:42 UTC, Sceat commented on test/player/resource_pack.test.js
> +    bot.once('resourcePack', (url, hash) => {
actually I should have used the promisified `once` here, will change

2022-12-22 16:48 UTC, DeltaEvo requested changes

2022-12-22 16:48 UTC, DeltaEvo commented on test/index.test.js
> +import Doubt from '@hydre/doubt'
Could we use the standard node test runner instead ?
https://nodejs.org/api/test.html

2022-12-22 16:48 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +          url: 'https://github.com/aresrpg/resourcepacks/releases/download/v1.0.1/addon.zip',
Hardcoding that here is very brittle, we should only check that we got a ressource pack and at best that it's downloadable

2022-12-22 16:48 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +    version: '1.16.5',
Should we not use the version from the settings ?

2022-12-22 16:48 UTC, DeltaEvo commented on test/index.test.js
> +const { default: server } = await import('../src/index.js')
Should we recreate the server for each test ?

2022-12-22 16:48 UTC, DeltaEvo commented on test/index.test.js
> +process.env.LOG_LEVEL = 'silent'
Not sure that's what we want here

2022-12-22 16:48 UTC, DeltaEvo commented on test/index.test.js
> +debug.app.close()
We should maybe listen for closes of the server inside debug.js instead

2022-12-23 06:46 UTC, Sceat commented on test/index.test.js
> +const { default: server } = await import('../src/index.js')
With "doubt" this one isn't a suite but the entrypoint so it only run once. But I'm gonna check the node test runner

2022-12-23 06:47 UTC, Sceat commented on test/index.test.js
> +process.env.LOG_LEVEL = 'silent'
We kinda don't want to whole server log conflicting with tests logs, it's there if someone have failing tests and need to dig but in anycase the output is not formatted

2022-12-23 06:47 UTC, Sceat commented on test/index.test.js
> +debug.app.close()
good catch

2022-12-24 22:25 UTC, DeltaEvo requested changes

2022-12-24 22:25 UTC, DeltaEvo commented on src/behavior.js
> +  if (debug_server) debug_server.behavior({ context: node_context, result })
I would prefer that we keep this global debug and that we make it null when a config option is set instead of hacking it inside the world

2022-12-24 22:25 UTC, DeltaEvo commented on src/context.js
> -  get: () => world,
You need to keep that here, otherwise the infered typescript type will not be the same

2022-12-24 22:25 UTC, DeltaEvo commented on src/context.js
> -const world = /** @type {World} */ (
The world by itself is immutable, you want to keep that and instead just recreate a new event emitter if you want to create multiple instances of it

2022-12-24 22:25 UTC, DeltaEvo commented on src/context.js
> -  position: world.spawn_position,
This can stay here or be transformed into floor1.spawn_position

2022-12-24 22:25 UTC, DeltaEvo commented on src/context.js
> -export async function observe_client(context) {
Could we not pass all the dependencies as arguments of this function instead ? The world and the mobs_position observer and create thoses in the server.js ?

2022-12-24 22:25 UTC, DeltaEvo commented on src/debug.js
> +function behavior({ mobs, app }) {
I would prefer us to keep the world here as we can extend it to read other properties

2022-12-24 22:25 UTC, DeltaEvo commented on src/player/item_loot.js
> +  if (aresrpg_item) {
We should not have invalid items in the first place, please remove that

2022-12-24 22:25 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +const KICK_REASON = [
We should not repeat this here

2022-12-24 22:25 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +  before(() => {
This should be a beforeEach, afterEach.

I would even prefer for us to create the server in the test and pass it as argument a signal https://nodejs.org/api/test.html#contextsignal to close rhe server when the test is finished

2022-12-24 22:25 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +    const { ok } = await fetch(url, { method: 'HEAD' })
Should we mock the ressource pack url to not depend on the network ?
Maybe add a todo ?

2022-12-24 22:25 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +    bot.end()
nit: use a signal in createBot instead https://nodejs.org/api/test.html#contextsignal

2022-12-24 22:25 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +    const client = options.client_by_username(username)
This seems weird and deems more to be a bug in node minecraft protocol, could you describe more what is happening ?

2022-12-26 06:04 UTC, Sceat commented on src/player/item_loot.js
> +  if (aresrpg_item) {
this means removing all items and mobs from the public world as they don't exist anymore, guess I'll do that

2022-12-26 06:05 UTC, Sceat commented on test/player/resource_pack.test.js
> +const KICK_REASON = [
hum this is arguable, it is the expected kick reason so if I source it from the code the test isn't that meaningful

2022-12-26 06:16 UTC, Sceat commented on test/player/resource_pack.test.js
> +    const { ok } = await fetch(url, { method: 'HEAD' })
I think it's fine during integration tests to depend on the network, it's even a good sign to catch problems early. Only in unit tests we shall be noop

2022-12-26 06:17 UTC, DeltaEvo commented on src/player/item_loot.js
> +  if (aresrpg_item) {
Well we don't care about the actual reason, only that the player was kicked if it refused the pack.
Asserting the reason make the test very britle making it fail when we modify the message where it should not as this will still function even if we modify the message.

2022-12-26 06:18 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +const KICK_REASON = [
Well we don't care about the actual reason, only that the player was kicked if it refused the pack.
Asserting the reason make the test very britle making it fail when we modify the message where it should not as this will still function even if we modify the message.

2022-12-26 06:20 UTC, DeltaEvo commented on test/player/resource_pack.test.js
> +    const { ok } = await fetch(url, { method: 'HEAD' })
The question then is this a unit or an integration test ? Because the boundary is very thin.
What do we consider as a unit ?

But it's not the subject, I'm mostly nitpicking, fine for me, you can resolve this comment

2022-12-26 07:58 UTC, Sceat commented on test/player/resource_pack.test.js
> +const KICK_REASON = [
depends if we test the concept of being kicked or the full intended kick including a strict message, both are fine so let's remove it to have a smaller code

2022-12-26 08:03 UTC, Sceat commented on test/player/resource_pack.test.js
> +    const { ok } = await fetch(url, { method: 'HEAD' })
unit tests are directly testing some functions, while integration include a wider behavior. It's nice to do both in Ares and it will just be differentiated as

## Unit
import the function from `src`, no IO

## Integration
run the server and only test the bot behavior

2022-12-26 08:28 UTC, Sceat commented on test/player/resource_pack.test.js
> +    bot.end()
createBot doesn't take a signal in its options

2022-12-26 08:48 UTC, Sceat commented on test/player/resource_pack.test.js
> +  before(() => {
actually the signal is never sent so we still need the afterEach to close the server

2022-12-26 16:07 UTC, DeltaEvo commented on src/server.js
> +export const world = /** @type {World} */ (
Keep the world inside context.js

2022-12-26 16:12 UTC, DeltaEvo requested changes

2022-12-26 16:12 UTC, DeltaEvo commented on src/context.js
> +  return async context => {
Take two arguments, when don't need to curry here

2022-12-26 16:12 UTC, DeltaEvo commented on src/context.js
> +        position: world.spawn_position,
Remove

2022-12-26 16:12 UTC, DeltaEvo commented on src/debug.js
> +  app.listen().then(address => {
Keep the port as is, it plays better with your browser history, if we have port clashes we could do something in the future to try to find a port near to the one we are used to (4243, ...)

2022-12-26 16:12 UTC, DeltaEvo commented on src/mobs/position.js
> +export default function mobs_position_factory({ mobs }) {
Why did you renamed that ?

2022-12-26 16:12 UTC, DeltaEvo commented on src/server.js
> +export const create_server = ({ signal } = {}) => {
Use a function instead of an arrow function

2022-12-26 16:51 UTC, Sceat commented on src/mobs/position.js
> +export default function mobs_position_factory({ mobs }) {
to keep consistency with import names. I like using default export but when the file is not a function like
```
get_x.js
```
```
import get_x from 'get_x.js'
```
the minimum required should be at least to name it the same way we use it, and here you used `mobs_position_factory` in the context. Otherwise we should not use default export as it will be confusing

2022-12-26 17:11 UTC, Sceat commented on src/context.js
> +  return async context => {
it allows me to
```js
create_context({ client, world })
      .then(observe_client({ mobs_position }))
```

2022-12-26 17:32 UTC, Sceat commented
PR is fully done, except for those broken typings
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11330271/209571921-fc9943b3-47d9-451f-bfaf-dc88cad839b4.png">

2022-12-27 18:18 UTC, DeltaEvo approved these changes

2022-12-27 18:22 UTC, merged