fix: Joining with an invalid version
aresrpg/aresrpg pull request #605
Opened 2023-01-17 18:58 UTC by SohKey

fix: #396

2023-01-17 19:08 UTC, SohKey commented on src/server.js
> +      mcversion: { minecraftVersion, version },
I dont know why `mcversion` is not recognized, i'm forced to use ts-ignore

2023-01-18 12:32 UTC, Sceat requested changes
This issue is more about fixing the problem in prismarine or wherever it is, and allowing players to join regardless of their minor versions

2023-01-20 12:53 UTC, Sceat commented
@SohKey I guess you can make some research work in here, but if it's not fixable on AresRPG, this pr should be closed

2023-07-28 12:26 UTC, Sceat commented
After some thinking, this is actually okay to have as a temporary fix. @SohKey can you just improve the `end` message similarly to https://github.com/aresrpg/aresrpg/blob/master/src/player/resource_pack.js

Note that later on we'll need to find a way to support multiple version of the same protocol

2023-07-29 14:07 UTC, Sceat approved these changes
lgtm

2023-07-29 14:07 UTC, Sceat approved these changes

2023-07-29 14:18 UTC, merged