Interact with NPCs!
aresrpg/aresrpg pull request #74
Opened 2020-12-20 15:53 UTC by ToufouMaster

Right click on an NPC and talk with them!

Added a detect_dialog(server, { client, world }) Function
Added a speak_to(target, server, { client, world }) Function

2020-12-20 17:47 UTC, DeltaEvo requested changes
Need some modifications

And i'm not convinced by the `linearity` feature I don't think we need that

2020-12-20 17:47 UTC, DeltaEvo commented on src/index.js
> +import detect_dialog from './dialogs/dialog.js'
This should go in `mobs` folder I think

2020-12-20 17:47 UTC, DeltaEvo commented on src/index.js
> +  detect_dialog(server, context)
Follow the same style as the other function by passing only one argument

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +}
Maybe this should go directly in `src/mobs/mobs.js` ?

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +      linearity: false,
`linearity` here is always false, do we really want this functionality ?

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +        )
This will send a message to all the players, I don't think you want that instead use `client.write('chat', ...)`

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +            ),
Please use the Object or Array format of a Chat Message https://wiki.vg/Chat

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +            ),
Please use the Object or Array format of a Chat Message https://wiki.vg/Chat

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +  const mob = floor1.mobs[target] // TODO: Replace with Client current World
This only works because `register_mobs` here is the first of the list https://github.com/aresrpg/aresrpg/blob/master/src/index.js#L32

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +    const mobdata = mobs[mob.mob]
I don't think `speak_to` should check that :thinking:, this should be done in `detect_dialog` I think

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +let dialog_text_id = 0
This should not be global, since this mean that it will break if we have multiple players

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialog.js
> +          }
This will send a message to all the players, I don't think you want that instead use `client.write('chat', ...)`

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +      name: '§a Citoyen §7',
Can you not use the mob name for this ?

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +          'PLAYER_NAME' +
You should replace this PLAYER_NAME and I prefer `{player}` instead

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +        "§fC'est incroyable ce beau temps !",
Can you try to avoid these magic color codes and instead use the color name in a chat component https://wiki.vg/Chat ?

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +    '-1': {
What is this `-1` ?

2020-12-20 17:47 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +export const default_dialog_id = -1
What is this ? I don't like this magic number

2020-12-20 17:53 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +        )
Thanks i go back to code

2020-12-20 17:59 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +      linearity: false,
if you want to create a character who told a little story to the player yep that's usefull
but if you don't it's useless

2020-12-20 23:57 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +      name: '§a Citoyen §7',
by what do you want it to be replaced?

2020-12-21 00:01 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +    '-1': {
-1 is global it allows to make the values ​​inside valid for all mobs
but if you add a "5917" and that you click on the mob with id 5917 the discussion launched will be the one named "5917"

2020-12-21 00:02 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +export const default_dialog_id = -1
it's the -1 in dialogs but you can change it

2020-12-21 00:02 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +      name: '§a Citoyen §7',
by what do you want it to be replaced?

2020-12-21 10:33 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +      name: '§a Citoyen §7',
I want that we use this https://github.com/aresrpg/aresrpg/blob/master/src/mobs/mobs.js#L428 instead

2020-12-21 10:34 UTC, DeltaEvo commented on src/dialogs/dialogs.js
> +    '-1': {
This `-1` is very weird, why not have choosen something like `default` ?
But I don't see this feature used, and id are not stable I don't like having id here
Since we don't use it I think this should be removed

2020-12-21 18:23 UTC, ToufouMaster commented on src/index.js
> +  detect_dialog(server, context)
Ok

2020-12-21 18:24 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +      linearity: false,
removed

2020-12-21 18:24 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +        )
Ok

2020-12-21 18:24 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +let dialog_text_id = 0
removed

2020-12-21 18:25 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +          }
Ok

2020-12-21 18:27 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +      name: '§a Citoyen §7',
Ok

2020-12-21 18:28 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +    '-1': {
removed

2020-12-21 18:28 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +export const default_dialog_id = -1
removed

2020-12-21 18:47 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +}
Ok

2020-12-21 18:47 UTC, ToufouMaster commented on src/index.js
> +import detect_dialog from './dialogs/dialog.js'
Ok

2020-12-21 18:48 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +            ),
I think it's Ok

2020-12-21 18:48 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +            ),
I Think it's Ok

2020-12-21 18:53 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +    const mobdata = mobs[mob.mob]
Ok

2020-12-21 18:55 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +          'PLAYER_NAME' +
Ok

2020-12-21 18:56 UTC, ToufouMaster commented on src/dialogs/dialog.js
> +  const mob = floor1.mobs[target] // TODO: Replace with Client current World
an idea of how change that?

2020-12-21 19:16 UTC, ToufouMaster commented on src/dialogs/dialogs.js
> +        "§fC'est incroyable ce beau temps !",
Ok
added in chat.js a const variable who has the 16 different symbol

2020-12-23 10:48 UTC, DeltaEvo requested changes

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/dialog.js
> +    })
I don't know if we want to use `chat.type.text` here since it's for player chat
```suggestion
    const message = JSON.stringify([
      { text: mobdata.name, color: "green" },
      { text: ":", color: "gray" },
      { text: mobdata.dialogs[x], color: "white" },
    ])
```

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/dialog.js
> +  }
Object.values([client]).forEach(send_packet) is the same as `send_packet(client) so I think we should just write
```suggestion
    client.write('chat', {
      message,
      position: Position.CHAT,
      sender: client.uuid,
    })
  }
```

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/mobs.js
> +      chat_color.white + 'Laisse moi !',
For the color this is not what I was thinking, you have two ways to have colors within chat, one with magic code (what you are using) and one with color names like in my comment above (`{ text: mobdata.name, color: "green" }`)

Here all the lines have the same color so I think we should remove the color from here and apply it on top, like in my suggestion :)

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/mobs.js
> +export const mobs_dialogs = {
By moving inside `mobs.js` I was more thinking about adding the dialogs into the current structure so for example change
```js
  thebes_citizen: {
    displayName: 'Citoyen de Thebes',
    type: 'npc',
    mob: 'villager',
  },
```
Into
```js
  thebes_citizen: {
    displayName: 'Citoyen de Thebes',
    type: 'npc',
    mob: 'villager',
    dialogs: [
      "C'est incroyable ce beau temps !",
      "C'est toi {player} ? Je pensais que tu étais plus grand !",
      "Fais attention à ne pas t'aventurer dans les catacombes, c'est dangereux !",
      "Je n'ai pas le temps de te parler, va t'en ou j'apelle la garde !",
      'Encore toi ?',
      'Un jour les dragons reviendront et ce sera la fin de notre monde !',
      'Laisse moi !'
    ]
  },
```

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/dialog.js
> +          text: mobdata.dialogs[x],
You need to replace `{player}` by the player name (client.username)

2020-12-23 10:48 UTC, DeltaEvo commented on src/mobs/dialog.js
> +export default function detect_dialog({ client }) {
The `detect` part of `detect_dialog` name bother me, I think just `dialog` is fine

2020-12-23 11:25 UTC, ToufouMaster commented on src/mobs/dialog.js
> +          text: mobdata.dialogs[x],
how?

2020-12-23 11:26 UTC, DeltaEvo commented on src/mobs/dialog.js
> +          text: mobdata.dialogs[x],
Using https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/replace

2020-12-23 11:27 UTC, DeltaEvo commented on src/mobs/dialog.js
> +      if (mob !== undefined) {
```suggestion
      if (target in floor1.mobs) {
        const mob = floor1.mobs[target]
```

2020-12-23 12:24 UTC, ToufouMaster commented on src/mobs/dialog.js
> +    })
Ok

2020-12-23 12:24 UTC, ToufouMaster commented on src/mobs/dialog.js
> +  }
ok

2020-12-23 12:25 UTC, ToufouMaster commented on src/mobs/dialog.js
> +          text: mobdata.dialogs[x],
Ok

2020-12-23 12:26 UTC, ToufouMaster commented on src/mobs/dialog.js
> +export default function detect_dialog({ client }) {
ok

2020-12-23 12:27 UTC, ToufouMaster commented on src/mobs/dialog.js
> +      if (mob !== undefined) {
ok

2020-12-23 12:28 UTC, ToufouMaster commented on src/mobs/mobs.js
> +      chat_color.white + 'Laisse moi !',
ok

2020-12-23 13:44 UTC, ToufouMaster commented on src/mobs/mobs.js
> +export const mobs_dialogs = {
ok

2020-12-23 17:09 UTC, DeltaEvo requested changes
Last round of comments and I think it will be good :+1:

2020-12-23 17:09 UTC, DeltaEvo commented on src/chat.js
> +
I think we can remove that since it's not used anymore

2020-12-23 17:09 UTC, DeltaEvo commented on src/mobs/dialog.js
> +}
`mobs[mob.mob]` is repeated a lot I think you should destructure it at the top of the function like that
```js
const { dialogs, displayName } = mobs[mob.mob]
```

2020-12-23 17:09 UTC, DeltaEvo commented on src/mobs/dialog.js
> +        const mob = floor1.mobs[target]
Can you add a FIXME ?
```suggestion
        const mob = floor1.mobs[target] // FIXME: check proper entity id here
```

2020-12-23 17:15 UTC, ToufouMaster commented on src/chat.js
> +
Yep
Ok

2020-12-23 17:42 UTC, DeltaEvo commented on src/index.js
> +// import { drop_item, collect_item } from './mobs/item_drop.js'
Remove this :)

2020-12-23 17:48 UTC, DeltaEvo commented on src/index.js
> -
Read this line

2020-12-23 17:53 UTC, DeltaEvo commented on src/index.js
> +
Remove that :)

2020-12-23 17:55 UTC, DeltaEvo commented on src/index.js
> -
Re add this line

2020-12-23 18:04 UTC, DeltaEvo approved these changes

2020-12-23 18:05 UTC, merged