Statistics
aresrpg/aresrpg pull request #78
Opened 2020-12-24 00:21 UTC by ToufouMaster

Basic Statistics System

2020-12-24 14:07 UTC, DeltaEvo requested changes
You branch contains also changes from your dialog pull request
We are only interested in the last commit
To fix that you can run
```sh
# We add a remote to fetch the data from the upstream repository
git remote add up https://github.com/aresrpg/aresrpg.git  
# Download data from upstream
git fetch up
# Reset the branch at the version from the repository
# This makes you "looses" all your changes, so be careful
git reset --hard up/master
# Reapply your Statistics commit
git cherry-pick 9debb450858d6ccfcf6618afb60d2db1c7bbdb0e
```

2020-12-26 15:57 UTC, ToufouMaster commented
Can you explain me how to resolve that pls Thx

2020-12-26 16:00 UTC, DeltaEvo commented
I already wrote instructions on how to resolve that

2020-12-26 16:01 UTC, ToufouMaster commented
> 
> 
> I already wrote instructions on how to resolve that

i did this but it does not work

2020-12-26 16:04 UTC, DeltaEvo commented
Does not work doesn't give me much information, can you be more precise ?

If I take my repo and execute each command I sent, I end with the expected result

2020-12-26 16:16 UTC, ToufouMaster commented
ok i retry this later

2021-01-10 08:59 UTC, DeltaEvo commented
There is still an issue with this pull request, a lot of files are modified

2021-01-11 10:34 UTC, Sceat approved these changes

2021-01-11 10:34 UTC, Sceat commented on src/commands/commands.js
> +}
This part seems verbose and ambiguous to me

### Sending
It should be consistent, if you send packets through `write_chat_msg` from external imports it should stay that way for the `default` too

### Matching
The `/` part is redundant, you can trim it and then directly apply the command option to the function name
ex:
```js
import command_error from '..'

const available_commands = ['like', 'dislike']
const to_entry = async cmd => [cmd, (await import(`./${cmd}.js`)).default]
const commands_entries = await Promise.all(available_commands.map(to_entry))
const commands = new Map(commands_entries) // ['cmd', function]

commands.set('gm', commands.get('gamemode')) // handling aliases

export default function execute_command({ server, message, sender }) {
  const [name, ...args] = message.trimStart().split(/\s+/)
  const options = {
    name,
    args,
    sender,
    server,
  }
  
  const command = commands.get(name.substring(1))
  if(!command) command_error()
  else command(options)
}
```

For the sake of readability you can be more verbose and directly use

```js
import like from '..'

const commands = new Map([
	['like', like],
	..
])
```

2021-01-11 10:34 UTC, Sceat commented on src/commands/gamemode.js
> +    sender: '00000000000000000000000000000000',
Could this weird magic be a constant sir ?

2021-01-11 10:34 UTC, Sceat commented on src/mobs/path.js
> +}
setTimeout has a promise version in node `15.5`

2021-01-11 10:36 UTC, Sceat requested changes
![image](https://user-images.githubusercontent.com/11330271/104170331-3cff5900-5401-11eb-872b-f3557ed7bf6c.png)

2021-01-11 10:37 UTC, Sceat commented on src/commands/gamemode.js
> +    sender: '00000000000000000000000000000000',
is it your bitcoin address ?

2021-01-11 10:41 UTC, DeltaEvo commented on src/chat.js
> +      if (part.match(/(%item\d%)/)) {
This code is already on master and a regex contain state this could break this code

2021-01-11 10:42 UTC, DeltaEvo commented on src/commands/commands.js
> +}
Already on master and `write_chat_msg` sends a message to all players, `sender.write` send it only to one player, we should rename `write_chat_msg`

2021-01-11 10:43 UTC, DeltaEvo commented on src/mobs/path.js
> +}
Yep but we use node 14 for now, I will wait for node 16 to be on a LTS

2021-01-11 10:44 UTC, DeltaEvo commented on src/commands/commands.js
> +}
cc @Zekirax (author of this code)

2021-01-11 10:44 UTC, DeltaEvo commented on src/commands/commands.js
> +}
For my part I like this switch, it's "simple"

2021-01-11 10:44 UTC, DeltaEvo commented on src/commands/gamemode.js
> +    sender: '00000000000000000000000000000000',
cc @Zekirax

2021-01-11 10:45 UTC, DeltaEvo commented on src/chat.js
> +      if (part.match(/(%item\d%)/)) {
cc @Zekirax

2021-01-11 10:47 UTC, Vahelnir commented on src/chat.js
> +      if (part.match(/(%item\d%)/)) {
aren't regexes without the g or y flag stateless ?

2021-01-11 18:36 UTC, Zekirax commented on src/commands/gamemode.js
> +    sender: '00000000000000000000000000000000',
It's my bank account password.

2021-01-11 22:36 UTC, Sceat commented on src/mobs/path.js
> +}
die potato

2021-01-11 23:00 UTC, DeltaEvo commented on src/chat.js
> +      if (part.match(/(%item\d%)/)) {
Mmh maybe

2021-01-17 03:29 UTC, closed without merging