Commands
aresrpg/aresrpg pull request #84
Opened 2020-12-26 17:01 UTC by Zekirax

add commands system and the game mode command.

2020-12-26 17:10 UTC, DeltaEvo requested changes

2020-12-26 17:10 UTC, DeltaEvo commented on src/commands/commands.js
> +      gamemode({ args: command.args, sender })
Maybe add the sender inside the `const command` to be able to just write `gamemode(command)`

2020-12-26 17:10 UTC, DeltaEvo commented on src/commands/commands.js
> +      break
```suggestion
    case '/gm':
    case '/gamemode':
      gamemode({ args: command.args, sender })
      break
```

2020-12-26 17:10 UTC, DeltaEvo commented on src/commands/gamemode.js
> +  const message = { translate: 'command.failed' }
`arguments.operation.invalid` seems more accurate

2020-12-26 17:10 UTC, DeltaEvo commented on src/commands/gamemode.js
> +function write_gamemode({ sender, gameMode }, { message }) {
write_gamemode dosen't seems to be an appropritate name since it seems do to more than "write_gamemode"

2020-12-26 17:10 UTC, DeltaEvo commented on src/commands/gamemode.js
> +      break
There is a lot of repetition here, I think this can be shortened

2020-12-26 18:42 UTC, Zekirax commented on src/commands/commands.js
> +      gamemode({ args: command.args, sender })
So I put null for uuid ?

2020-12-26 20:27 UTC, Zekirax commented on src/commands/gamemode.js
> +function write_gamemode({ sender, gameMode }, { message }) {
-set_gamemode
-write_gamemode_and_message
-write_gamemode_infos

Who's the best?

2020-12-27 14:49 UTC, DeltaEvo requested changes

2020-12-27 14:49 UTC, DeltaEvo commented on src/commands/commands.js
> +}
I think we can inline that inside `execute_command`

2020-12-27 14:49 UTC, DeltaEvo commented on src/commands/commands.js
> +  sender.write('chat', options)
```suggestion
  sender.write('chat', {
    message: JSON.stringify({ translate: 'commands.help.failed', color: 'red' }),
    position: Position.CHAT,
    sender: sender.uuid,
  })
```

2020-12-27 14:49 UTC, DeltaEvo commented on src/commands/commands.js
> +    command_name: splited_message[0],
`name` is enough I think since we are already in `command`

2020-12-27 14:49 UTC, DeltaEvo commented on src/commands/commands.js
> +  }
```suggestion
  const [command_name, ...args] = message.trimStart().split(/\s+/)
  const command = {
    command_name,
    args,
    sender,
  }
```

2020-12-27 21:20 UTC, DeltaEvo commented on src/commands/gamemode.js
> +  const { message, gameMode } = gameMode_options[args[0]]
```suggestion

  const by_name = args[0].toUpperCase() in GameMode && args[0].toUpperCase()
  const [by_number] = Object.entries(GameMode).find(([,id]) => Number(args[0]) === id) ?? []
  const mode = by_name || by_number

  
  if (!mode) {
    write_error({ sender })
    return
  }
  
  const message = {
    translate: 'commands.gamemode.success.self',
    with: [{ translate: `gameMode.${mode.toLowerCase()}` }],
  }
  
  const gameMode = GameMode[mopde]
```

2020-12-27 21:21 UTC, DeltaEvo commented on src/commands/commands.js
> +export function write_unfounded_command({ sender }) {
Inline this into `execute_command`

2020-12-27 21:21 UTC, DeltaEvo commented on src/commands/gamemode.js
> +  sender.write('game_state_change', write_gameMode_options)
```suggestion
  sender.write('game_state_change', {
    reason: 3, // game_state_change is not only for gamemode but for a lot of things. And 3 is for gamemode.
    gameMode,
  })
```

2020-12-27 21:22 UTC, DeltaEvo commented on src/commands/gamemode.js
> +  sender.write('chat', write_message_options)
```suggestion
  sender.write('chat', {
    message: JSON.stringify(message),
    position: Position.CHAT,
    sender: '00000000000000000000000000000000',
  })
```

2020-12-27 21:22 UTC, DeltaEvo commented on src/commands/gamemode.js
> +  sender.write('chat', options)
```suggestion
  sender.write('chat', {
    message: JSON.stringify({ translate: 'arguments.operation.invalid', color: 'red' }),
    position: Position.CHAT,
    sender: sender.uuid,
  })
```

And inline it :)

2020-12-27 21:43 UTC, DeltaEvo approved these changes

2020-12-30 13:27 UTC, DeltaEvo approved these changes

2020-12-30 13:54 UTC, merged