Basic screens implementation
aresrpg/aresrpg pull request #90
Opened 2020-12-27 21:53 UTC by loucass003

2020-12-29 20:44 UTC, DeltaEvo requested changes

2020-12-29 20:44 UTC, DeltaEvo commented on package.json
> +    "start": "node --inspect=0.0.0.0 src/index.js | pino-human",
Maybe add a `debug` script for that or remove it :)

2020-12-29 20:44 UTC, DeltaEvo commented on src/index.js
> +  screens: [],
This should not go here, can you not create it inside `register_screen` ?

2020-12-29 20:44 UTC, DeltaEvo commented on src/index.js
> +  game_mode: 1,
Revert this change :)

2020-12-29 20:44 UTC, DeltaEvo commented on src/login.js
> +  events.once('state', async (state) => {
async dosen't seems to be used

2020-12-29 20:44 UTC, DeltaEvo commented on src/login.js
> +    screen_pos.y += 15
```suggestion
    const screen_pos = { ...world.spawn_position, y: world.spawn_position.y + 15 }
```

2020-12-29 20:44 UTC, DeltaEvo commented on src/login.js
> +    ctx.fillRect(0, 0, size.width * 128, size.height * 128)
Maybe we should introduce a create_screen_canvas for that ?

2020-12-29 20:44 UTC, DeltaEvo commented on src/login.js
> +    )
```suggestion
    const { size } = get_screen(world, 'player_screen')
    const canvas = createCanvas(size.width * 128, size.height * 128)
   
    const ctx = canvas.getContext('2d')
    ctx.fillStyle = 'black'
    ctx.fillRect(0, 0, size.width * 128, size.height * 128)
    
    pipeline(
      () => on(events, 'screen_interract'),
      reduce((old_canvas, { x, y, screen_id, hand }) => {
        const canvas = copy_canvas(old_canvas)
        
        const ctx = canvas.getContext('2d')
        ctx.font = '30px arial'
        ctx.fillStyle = 'red'
        ctx.beginPath()
        ctx.ellipse(x, y, 10, 10, 0, 0, Math.PI * 2)
        ctx.fill()
        
        update_screen(
          { client, world },
          { screen_id, newCanvas: canvas, oldCanvas: old_canvas }
        )
        
        return canvas
      }, canvas)
    )
```

2020-12-29 20:44 UTC, DeltaEvo commented on src/index.js
> +  screens: [],
But I think it's unused since you recreate an object

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +      }
Use buffer.equals

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +  for (let frame = 0; frame < size.width * size.height; frame++) {
Why not create two loops with `x` and `y`

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +      }
Maybe we should use the A8 pixel format to remove that https://github.com/Automattic/node-canvas#image-pixel-formats-experimental ? and avoid to do copies here

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +  return { newCanvas }
I think we don't this return :)

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +  { screen_id, newCanvas, oldCanvas }
`new_canvas`, `old_canvas`

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +}
I think this function is not needed since we can do `world.screens[screen_id]`

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +  const imageData = old_canvas
`image_data`

2020-12-29 20:44 UTC, DeltaEvo commented on src/screen.js
> +}
Maybe transform this into an utility function that return the hit or null instead :)

2020-12-29 20:44 UTC, DeltaEvo commented on src/settings.js
> +export const version = '1.16.4'
Revert this change :)

2021-01-06 18:34 UTC, loucass003 commented
I Fixed this PR with your feedback

2021-05-03 17:54 UTC, loucass003 commented
Shoud be all good this time ;)

2021-05-03 18:47 UTC, DeltaEvo commented on src/player/screen.js
> +      }
```suggestion
      let different = true
      const new_image_data = new_canvas
        .getContext('2d')
        .getImageData(128 * frame_x, 128 * frame_y, 128, 128)
      const old_image_data = old_canvas
          ?.getContext('2d')
          .getImageData(128 * frame_x, 128 * frame_y, 128, 128)
      const different = old_image_data && Buffer.from(old_image_data.data.buffer).equals(
          Buffer.from(new_image_data.data.buffer)
        )
```

2021-05-03 18:50 UTC, DeltaEvo approved these changes

2021-05-03 18:52 UTC, merged