Red_Screen Control
aresrpg/aresrpg pull request #93
Opened 2020-12-28 22:19 UTC by ToufouMaster

Added Red_screen Control Function

2020-12-29 20:23 UTC, DeltaEvo requested changes

2020-12-29 20:23 UTC, DeltaEvo commented on src/login.js
> +import { set_world_border, red_screen } from './lowlife.js'
I think since it deals with border this should be named `world_border.js`

2020-12-29 20:23 UTC, DeltaEvo commented on src/lowlife.js
> +  client.write('world_border', { action: 2, x: 0, z: 0 })
`x` and `z` should be passed as argument

2020-12-29 20:23 UTC, DeltaEvo commented on src/lowlife.js
> +  client.write('world_border', { action: 2, x: 0, z: 0 })
action 0 & 2 can be combined in one action 3 https://wiki.vg/Protocol#World_Border

2020-12-29 20:23 UTC, DeltaEvo commented on src/lowlife.js
> +  client.write('world_border', { action: 0, radius })
I think we should define an enum for the actions

2020-12-29 20:23 UTC, DeltaEvo commented on src/lowlife.js
> +}
If this function is for turning the screen red I don't think that we should pass a warning_blocks to it

2020-12-29 20:23 UTC, DeltaEvo commented on src/login.js
> +    set_world_border({ client, radius: 10000 })
Instead of `10000` we should use the map dimension, `0 0 1020 1020`

2020-12-29 21:00 UTC, ToufouMaster commented on src/lowlife.js
> +  client.write('world_border', { action: 0, radius })
an exemple pls

2020-12-29 21:01 UTC, ToufouMaster commented on src/login.js
> +    set_world_border({ client, radius: 10000 })
1020/2 = 510 radius

2020-12-29 21:19 UTC, ToufouMaster commented on src/login.js
> +import { set_world_border, red_screen } from './lowlife.js'
ok

2020-12-29 21:20 UTC, ToufouMaster commented on src/lowlife.js
> +  client.write('world_border', { action: 2, x: 0, z: 0 })
ok

2020-12-29 21:20 UTC, ToufouMaster commented on src/lowlife.js
> +  client.write('world_border', { action: 2, x: 0, z: 0 })
ok

2020-12-29 21:22 UTC, ToufouMaster commented on src/lowlife.js
> +}
ok

2020-12-29 21:22 UTC, ToufouMaster commented on src/login.js
> +    set_world_border({ client, radius: 10000 })
ok

2020-12-29 21:54 UTC, DeltaEvo commented on src/lowlife.js
> +  client.write('world_border', { action: 0, radius })
https://github.com/aresrpg/aresrpg/blob/master/src/chat.js#L11-L15

2021-01-10 08:55 UTC, DeltaEvo requested changes

2021-01-10 08:55 UTC, DeltaEvo commented on src/login.js
> +    set_world_border({ client, radius: 10000 })
Some parameters seems to be missing `x`, `z`, ...

2021-01-10 19:38 UTC, ToufouMaster commented on src/login.js
> +    set_world_border({ client, radius: 10000 })
oh i see why it does'nt worked

2021-01-11 10:50 UTC, DeltaEvo commented on src/login.js
> +    set_world_border({ client, x: 512, z: 510, radius: 10000, speed: 1 })
Instead of 10000 we should use the map dimension, `0 0 1020 1020`
And why `x` and `z` are not equals ?

2021-01-11 10:50 UTC, DeltaEvo commented on src/world_border.js
> +  SET_WARNING_TIME: 4, // i don't know (default : 0)
```suggestion
  SET_WARNING_TIME: 4, // (default : 0)
```

2021-01-11 21:00 UTC, ToufouMaster commented on src/world_border.js
> +  SET_WARNING_TIME: 4, // i don't know (default : 0)
xD

2021-01-11 21:01 UTC, ToufouMaster commented on src/login.js
> +    set_world_border({ client, x: 512, z: 510, radius: 10000, speed: 1 })
i will fix that sry

2021-01-17 22:28 UTC, ToufouMaster commented on src/login.js
> +    set_world_border({ client, x: 512, z: 510, radius: 10000, speed: 1 })
ok

2021-01-17 22:28 UTC, ToufouMaster commented on src/world_border.js
> +  SET_WARNING_TIME: 4, // i don't know (default : 0)
ok

2021-01-17 22:58 UTC, DeltaEvo approved these changes

2021-01-17 22:59 UTC, merged