Adding new Reaction Commands
aresrpg/aresrpg pull request #99
Opened 2021-01-07 23:47 UTC by ToufouMaster

/rt /tg /thug /ragequit...

2021-01-08 06:51 UTC, DeltaEvo requested changes

2021-01-08 06:51 UTC, DeltaEvo commented on src/commands/ragequit.js
> +  sender.write('kick_disconnect', { reason: JSON.stringify('§ert si c trist') })
Use `client.end` here like un ressource_pack.js
And create a json chat instead of using color codes

2021-01-08 06:53 UTC, DeltaEvo commented on src/commands/f.js
> +export default function f({ sender }) {
Maybe name this file and his function fragile instead

2021-01-08 06:54 UTC, ToufouMaster commented on src/commands/f.js
> +export default function f({ sender }) {
good idea

2021-01-08 07:30 UTC, DeltaEvo commented on src/commands/dislike.js
> +  sender.write('chat', {
Using that the chat message is only sent to the player that have issued the command, use the function inside chat.js to send it to all the players

2021-01-08 07:32 UTC, ToufouMaster commented on src/commands/dislike.js
> +  sender.write('chat', {
hum i remember having an issue with chat.js function but Okay i will try that

2021-01-09 23:22 UTC, ToufouMaster commented on src/commands/ragequit.js
> +  sender.write('kick_disconnect', { reason: JSON.stringify('§ert si c trist') })
Ok

2021-01-09 23:35 UTC, ToufouMaster commented on src/commands/f.js
> +export default function f({ sender }) {
Ok

2021-01-10 00:01 UTC, ToufouMaster commented on src/commands/dislike.js
> +  sender.write('chat', {
Ok

2021-01-10 08:52 UTC, DeltaEvo approved these changes

2021-01-10 13:13 UTC, merged